apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: ntfy
spec:
  interval: 15m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      ntfy:
        containers:
          app:
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /v1/health
                    port: 80
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  failureThreshold: 6
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /v1/health
                    port: 80
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  failureThreshold: 3
            image:
              repository: binwiederhier/ntfy
              tag: v2.18.0
            args:
              - serve
            env:
              TZ: Europe/Amsterdam
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi

    service:
      app:
        controller: ntfy
        type: ClusterIP
        ports:
          http:
            port: 80
            targetPort: 80

    persistence:
      config:
        type: secret
        name: ntfy-secret
        globalMounts:
          - path: /etc/ntfy/server.yml
            subPath: server.yml
            readOnly: true
      cache:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /var/cache/ntfy