apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: ntfy
type: Opaque
stringData:
    server.yml: ENC[AES256_GCM,data:0ekQMrheb0N7kRZNJEC5+/9JAMclKyj4jC3Qalfm6EWMRUXd9+FAkf9/0CUExMc5GBRJ83umgGEp5xyxqHb7o32zTCv5UiwEHV1tvnFQWb26yTsUtB1QaYsV8x5612HB5RXD6kFpJYDYAly9sfuxB1qmOa0S9bRDGGqdRghrodTn8DZtXPzh9y9mIdAOllZswH63tRFJzYqOqTVo8HpWVatgypc3m+FPwxs87A7e0dPl4bq05acLmtm40naHxfPxnVYelNXY/EbIVwCvW/l0pxflOdIT/goNP3svOBXnYXuDIfmdjM5wp9NyLSwBRA9Ts4txPS2FuDRfSCUsSF1Dsi21cLTG5EkjrTZbxXgwUQlzIZnyChEJ/zZuf+fXuX1J7ym0keCgAk6bRouj9DJiqIKVc0t/bkfMqxvW+LO7Uihs9q+BSWXtYSszMuqHI7ptZd5qwck+FWGvDJZT7GpxdM/EPUs/6G9FkDrjpdzeXxZgP5f0rqcI93DsxFoilqYVVc/h0pwNjKyomyMvYu2N39mAx6SXcOdU4vKb2p5tDdHYwKpjHVUC7e/FjIu8MHswrLRhi+BMo1Ur/8mTH6IPIiHYcWDuPq5Eanq2pnEO0Ji6JvFL9HmlHmCDwb0q0f+E53La7SwH1qxZJ1PrfZ+Nr3PPgJuyEVuCZNqW3XjpvrHLLkfmdhEr6jHHKnniiWMmVqgBPbsdfXn38M4cPYfmxGxg0s4XqO7S3NRplNvb4qTFxxmete5z1Ex5c6S2tjdFPpuWc/oki+9pJ5GT3rL+hadlc6qf9/hNfX/0I+X4ksOeWBeG7qH+ygCxzk3n3NSwPsC40xcdPwks5niIi2zm9mXlJTNAr0B4chu9AQwXhhZ9kgnjBqs0fcHDBXsNkEODeH+KFY2CgrxKt404PUa0q9Z74LV/Rc/ebZZvH1/0Y+gnvzrbf1H2bbhtV/RNWmv+jw9Mgbr9kfMPFDBK6Q5HCPYxC8BleAbbZZcWvxgpz7nTbvFgu7A9g/KVYjZuc034ph2902MU9+PadcfxyDKqlTws0lSXKQvrCPK7p6zbMa6MplOHbnZivZ5LYdm/sF5h1ax3EKtnFaE9Xa/gsOOBwgi3Z5dUHkvpZ22OYrD1P3SwzHRobDk=,iv:Z+pI8VNZwb5S7FPyd3gl/zKgfTnPN1h8b8/KkTlMmpA=,tag:naGPLcELYwIisaX57G8uBQ==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdjJzcDdvZSttakhnRXBx
            R3hjeVkzamtyQU9NY1BmekRuQndlZzVKazFJCnhhNi9UMjNndWRTbW5rbzZTbzM3
            aFNXcXF2bUlYcmNYeVlWbnpWTUhwNlEKLS0tIFRiQStJTDFqNXlkQmpJZFlnTFZm
            K2VhNGk2N0pTQ3ZEQWxuSWljT0dHSG8KfbYfr60uDnORboLTsYgJ6yz077gXMuuY
            4w70G/4opgsgCgVbU8lx87d787fGfUay8GeNyLroJVH4bWFBaSBKgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T21:06:15Z"
    mac: ENC[AES256_GCM,data:PmHEDDWWuIyKYkAR4OE7fk/ZorU3Xf4dIsEU+NVq/eTNqEaSQPBTD/GIMokgcNz8NiNQtgVSxgUCVDxj/NBCwleHiAvxJ5hepVTGAsnCoGF5bZejR6CCsdwI4T2n0IYHx2TC2ZG5/vzXJ5hqDVKdtWFDOZSZsp3znYJcQEtpfew=,iv:01OTlwgY9GgiEpBLX5yvLKWY9gpNwrT4IuLPn6OIyI4=,tag:FvcO9JAdGFE8t2W1YZZggw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
