# apps/talos-home/ntfy/secret.yaml
# Encrypt with SOPS before committing:
#   sops --encrypt --in-place secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: ntfy
type: Opaque
stringData:
    server.yml: ENC[AES256_GCM,data:CEXtg6F7ZyFbqN8VtD7QH/85tDfRwWRgx/RHsUW6p3xRGx8hibWsTYND0PcQol0D4nvrZalHnOzk3Lo8n3HLknbwpFHlWfPQ85QgHX4A+5ue8t8wBeBu8AanrnLpltDPpr+p2DyuW4mtLCXaVUTzjVBvlGbuqgofMsj8hzWGXbjNyGPASGJuz3Jmu34squ/cxkjf+pklkw1UpNbOGZoknBySIve/u2tQ8GAbl2WtY8EM9B/p5o7UPYZyAeANhW7E+5vuzChQeAVCApC9l+FDpqwsPTQMU/1NoWIhWbjbXjkxqxxPwcDGYraXGxF95y88P6u2aiBf0njzx7GegLv99+D0K3JpExdjuNffHoI9a7h0MBXFUMeGa6cuAWFbRn6Wxw3Zejyc2RCfDsHE35Y9eL350Hjak1dxP6uMXIsN9oFJu9gEJum3WXfemrDyFp8EkZwDamzEuIjhhZM11QwcQsdKOnPviM5Kvr01ctbfqcD3cguTjojAJ0llzlcWgx03l7QukcT6u1Gv1fic3VHrJ2X2lyagEqor+wMrpV+HScNGXoFXivco0bMpNQSBfyh5Q16AoaNNzhQtlJLtCdiMZeGgdURA6NfD7TVYw6S5NDzo2qK0kgMbb2u2nxqqfuGQwYfhKZ77Z6r+K5GQ96IXRVWt1HFr2jPtrCQaOk8NZtjMXEFsmN1fOt5w+6lTbBXodUtrECfn3+Awy5Hn/HnWVok9YXqvVCQip7U862ngYng5GaeWX0GIWu2KNNvBFWxoauPtsWHEwVXNnifXmT2AqtJWrAO+X8kaSSei9cUzjpUhtkn7jzRiKnBtNoQn3BakDtuWXBTBzZ5wAM7vouADK0aZcBI8ManfSWnJ9jUjC5sFvkV0sDElHejaWUrGvmB+Q7Qe6HK1WMHzu+ZdaIpXmUZs/xYoCRWq+wpKBAOof60Ur1Ue8Dx8PfQb6YloXXRRgz9xHJExAL4aKJ9iZK8aOXzDjYcP4uk3IyosiBst5fcM3VrjkmcVaBQSf2at0VA76jb5FX9n9CKsoeJ6x4X4MHdUnQtvv9KM0/69NYlWk8SRVNNVW4QURaeDa0wswYP07aTabkhjCGqNb8swCvD+92LfQdCLqJs3iYcwSdgNBL0/+6VrNI8RniMxJvieN9WtP7NrUJbfdnzI0mlQTSbTCFQq/Ttgvcr+LPsTtC56PA/4D1KCsMtUx9ZLWg==,iv:Ku2wA6T1m9/3r0N/rfHYOsOkZjoXoUAGdEkERs7oido=,tag:WO68VWK6rkM+cp9k26X5PQ==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSFVqZ1VhbWxFanRsNk85
            MGxIMGs1bmlVaVhyd1FLQ05saXhNYjJnRjFBCmE1TEZsd09oaW5DU0MrWkh6cUYy
            YW82UmdSYkFseDVkT0N3YnpmVTlYY0EKLS0tIFNzZnBUZXFrMDdtVlppT3I2SlRD
            K0tsOWJDME1Xb24wN21ucGVHOEh6dk0Kc4ar7X0PD8lYjCLQg4vrDR0Z5vQ1yJaH
            BRNdNlR9xxvbbQbtnAu/KAMGNZzmvJYT8auz4IhYpqHBmaW98/7fZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T22:45:13Z"
    mac: ENC[AES256_GCM,data:FXDdLGB6A9X8I4XLlwCTNTRl3TB5yOtMG4aGjxmdt7PhW3WyQBwnCH63eq7gtNttLOfmGWYl/OZ4tk81/I3NLtVBhUEkwPS5hEa4RQOgvcQMXPlrl1np2XDbS5wT2TCf4Gd459JMRvvQsMjjdnlUpBJNIuxelMxkZqqCtRb7EwE=,iv:dIdUl4/toXNp1x/hTFCXX7qlo4YZvw0cjdZbeCInNn0=,tag:v7ZmIH1KV+UuG0zeNc/Gog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
