# apps/talos-home/ntfy/secret.yaml
# Encrypt with SOPS before committing:
#   sops --encrypt --in-place secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: ntfy
type: Opaque
stringData:
    server.yml: ENC[AES256_GCM,data:BNLP+lKm+YnZaC0a96x7mfCneBF4K0z7+zedHfP6/hyJOmFU918nGIqFsmvYRdts8UZNEI3alXY7ev+1VXFgaQkoo4CvM0NBArkUI8eUj6KpR/H+B0nX48a4PZ+LN+S06hI2vLiV1OVIei/4iWb7ZRrPVUnlICP/OQAFAunQnSGOWvHv472MQFrTdUaYSPdm7yMxDFs9YZmRTg7/QDNdhSnFj1kXqGsriKpySb5Qv/6RwPdMO3fnilJqYXLEyVxHgKrH1+wLgDYYY6PAKWj1qNI3rfPZ+4Q3WHrXOVq7Z56f03s0/gt4pLznzpoZglZw1Qzs5Xj373NpibKXpnjieIcB0eWfO4x0Ch6SIDAfK8zTDulWjnG19+vVCVWhmy4YUgGGbIUI/syNAhOC7hbo1Na+j+v2bVzQgKswX0W76bifG5WbOLBJGcOINMT9ht8H8oHYy6lSbqFdEjI8GKUpr3cXlOkoE6sMHZVLosBXKXK7dzxVaVZm416FyA3W1la4ANM7UXC9hsCxvWJqjU19Q3at+h72Za+uzg1luDBr3bZYc2HAj+A1BQ+uC86ToBQFXeFmByrUd9YF0nBCK7EeOgjgy4ZF9MaKciL0mbuqF/vjNZuFXsZ33TAF5Dymd7VpsbQrpxvAnaptYNtXc6Mn2azNDgv2iajNVPJwnMGP9obyeTlSqo33isBWObeUr9oIjqkDgywebRW1OjfVLnaNmC/4HgLg/oP6xQqfsyXXoQpGnYGqAdwzjfQRLRciQP9MyQSD8RVIu0n9sG4ZWpZHVzPmC9T91V/xCjO9T7/6ylFlmxSnc+1w8pzJ7JmC/wx5uro+3cMObHgkYSvF3M348A5sv7X3qhdXMmFElJKqOui2XXOb5afq6ibI76TW027H9ayL1OUANb0P2sTQE7IAThSafBX9wmEJxnsoHnblvV/o85HZWmrwLkntEegzgZwpyFIpNp4htaCckzNqFA/YPcY74BHFSi0ovqP5tjzTDtSQ79BrTezrKPVJRH/qGDJdZw/e2wEWIl2TFfxhjiImwJaJGHpGolPHfxKPtW+2cpCw,iv:5sNjkS9nhM+qO31te79dKHbyvob/2GShebWhmtBwe3E=,tag:odXdDvCYMdNlM/fBL/NQMA==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cXR5MXFOa2FnK2RSNjQz
            a1dRL2szZG14dUlmVVgrcW5meXY0N3dhNlZzCmdHZENjQnlUbnQ1V2RYRHVZMDZv
            UnQzL3A2cWlXWGFlMjg3S0xWd1VrUEEKLS0tIDVxUXU3SmJydDFYMXVSdlpzc28y
            by9LMDlXSzRmeFVFRXExOVNlckptR1UKJIHdHHK3IInSjUYqQNRCu7n2AN+Ivas+
            LoO00Mc4TRQx/lGz+5dszy9RqLyJ28cmFkGGnLcot1l6OZ5K5y8/ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T22:30:43Z"
    mac: ENC[AES256_GCM,data:ffbzkp+g63SNMH3/M8tEXqDkTorRds6uYPOPzrDwjhXSp6fNBn/8grwFChvqBxsEfEiQX9+DGXQ9YywpKhRSFzuazBiu5xcebCdc/W+AIzkl9EkRGpm6Os92jc8FiXYAixf26o9fwwqB9yClrQFCkN/B4NmGGLU5sRXEvuCZKKM=,iv:RFZL+UxT9Ew4UWCX3WNISxORDGBf/GLdVK5uyYS2zGw=,tag:DGNOS4ZHa9fjf5M4zKTSzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
