apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  image: louislam/uptime-kuma
  interval: 12h
  secretRef:
    name: dockerhub-credentials   # optional but recommended to avoid rate limits
