apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-credentials
    namespace: uptime-kuma
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:mb6O,iv:Xt6lHK3YXryhNl1ziUrdUIB9hupbQ4geHSDdyRfcRGI=,tag:eL2jrBhAkygB4XxvIWuo9Q==,type:str]
    admin-pass: ENC[AES256_GCM,data:A1JKo/+VoGH0iXrFwbk=,iv:DTdBvpQsrIrIPqGvOgn4nVsso5ccE5/qZA/uOSGjecs=,tag:If3N5oRrgZrVxoRuKzizvQ==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOTZsN0RTZHpEbXVxNHY3
            MWpFLzY3QVB1dXBNbEJVYi9LQklQeGwrRm1VCmVTek5jR2R6c3Y2Z0h6UjZGL3ZR
            ZjBPOXhCcGxTR2VUdldLTXRDZlRXMmcKLS0tIFc5NjJXejhwYkF4ZXRWMlFvY2VO
            enY1bHVzbzlZdEdxOElacFlpc0JCd2MKijn1oiCt52eNKd28p4gebYyFvvWy90lc
            RYu/o4Y5syjE1W9ZsNhraOqGvX9GQjD66wSsy4heenrJ5186OBzl6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T12:52:08Z"
    mac: ENC[AES256_GCM,data:n3a3FOvPNBzQiN0qsgvHGhHEfMHFLPpXwfe/GtFeHuQfXbVXWYdhHlWiOP+zpvUqBLvqc1SHPPjG4nUg2TDxbiYUlMzyVEjI7qLse4k+aFzl1bYeF04cp+aGmbn4ohZrZ7xossxfq9RXeAGxpbZuPwTxU9JDuWBC62Jwsv4kZLE=,iv:lG/E3eR60ijlDiy88REJyv5lKRDSvzUN6FL0Tt1v/Lg=,tag:HDHkTjyuC5qEJzpy0TjFjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
