apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-credentials
    namespace: uptime-kuma
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:IE7UERI=,iv:jo1aksjwxgBH7BruCNgM6liRQhYCMBH8K/RNSkzqxw4=,tag:lM4CKlkfF9qoaipv4o4I2w==,type:str]
    admin-pass: ENC[AES256_GCM,data:gvGSMd9vCX5ZMeGkt2E=,iv:2cJcMn+6HcodwR1egQ3pBnaiF62aNzaWzNdcN0yBWcY=,tag:XRF2af2zCZ6E0sI8bL2vVg==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb2ZHTWZ2MCtoejltaVV5
            RC9HVzloRkk4YVVvUjNxdGlvKzhiTW4zbTNFCitBbGJYclBKNnRQNnhSS0tSWURM
            MGlGbTQ3T1FtdzduR1ZkejVxZ0NhRjQKLS0tIDN2R1BSRHRSVHhVYmU2ck1QMXZV
            K3JEcnhGN3JaeTM2NUtQZExHTmRsY0kKiiDA4TsF7MoRLqjDcj55PaKg2gjuHZTq
            lLPHxt+fNRcK7khZTIOSj7brTbnaQovOtDy3GBHru5V9l/yLRkNXKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T20:22:56Z"
    mac: ENC[AES256_GCM,data:f4LnWC1FblHVCQFhyLGivOMf27HiW82HMEr+COBLqbLGLegX4AJGmdhNhkn+X9sPLlWDQMsJ6RI+uH+/6FP1bY84ZILs/TOlgw5SnmG4YwsSfh5G89gN32OVBkwQj1eGerwU8o0mhMOR42TSCVZR/J6H+GyEY13gVU9YIUI8X/o=,iv:gjize2D1mDuN9hpiU/rOlmv38N0VA7YoDNYbp40qvD0=,tag:78GRG6D/4DxoOJC+OUYp/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
