apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-credentials
    namespace: uptime-kuma
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:mb6O,iv:Xt6lHK3YXryhNl1ziUrdUIB9hupbQ4geHSDdyRfcRGI=,tag:eL2jrBhAkygB4XxvIWuo9Q==,type:str]
    admin-pass: ENC[AES256_GCM,data:A1JKo/+VoGH0iXrFwbk=,iv:DTdBvpQsrIrIPqGvOgn4nVsso5ccE5/qZA/uOSGjecs=,tag:If3N5oRrgZrVxoRuKzizvQ==,type:str]
    gotify-token: ENC[AES256_GCM,data:HC+ugXw868GlS45GNvEB,iv:hXTuElfYBBeNGEdB0zAG+5oRyRZ8tNKsKv6/FE/hLgk=,tag:Qr1uWgqA9Mhcdt4fJhLIBA==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOTZsN0RTZHpEbXVxNHY3
            MWpFLzY3QVB1dXBNbEJVYi9LQklQeGwrRm1VCmVTek5jR2R6c3Y2Z0h6UjZGL3ZR
            ZjBPOXhCcGxTR2VUdldLTXRDZlRXMmcKLS0tIFc5NjJXejhwYkF4ZXRWMlFvY2VO
            enY1bHVzbzlZdEdxOElacFlpc0JCd2MKijn1oiCt52eNKd28p4gebYyFvvWy90lc
            RYu/o4Y5syjE1W9ZsNhraOqGvX9GQjD66wSsy4heenrJ5186OBzl6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T18:54:28Z"
    mac: ENC[AES256_GCM,data:ggMp+IPWIAKAfHm+rNvj24qUxhTx1y1QmWvxuCRrfv5eyz7MCNGsJa8W2fXZ/FSszS8hnk/NFc9PiwSq9IcWxLJxgJTUBtD/6hLKnWXhwgfKJbPi/rFESVQuV3vy+M/TJQC2CyRSIlsDYAssRHDU8neg73UEH5k7PNcJ4XhbZas=,iv:HHvSUCDzeZBwOxceHhnkyKrtCMR6+aV4K7BbSDoiKX4=,tag:9lLBlZklY/q+u/abubSVKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
