apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashy-tls
  namespace: media
spec:
  secretName: dashy-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - dashy.lan
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
    group: cert-manager.io