apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashy
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dashy.lan`)
      kind: Rule
      services:
        - name: dashy
          port: 8080
  tls:
    secretName: dashy-tls