apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: dns-pool
spec:
  blocks:
    - cidr: 192.168.2.53/32
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: traefik-pool
spec:
  blocks:
    - cidr: 192.168.2.100/32
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: core-pool
spec:
  blocks:
    - cidr: 192.168.2.101/32
    # add more entries here for multiple blocks/ranges, e.g.:
    # - cidr: 192.168.2.102/32
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: jellyfin-pool
spec:
  blocks:
    - cidr: 192.168.2.50/32