apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: dns-pool
spec:
  blocks:
    - cidr: 192.168.2.53/32
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: dns
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: traefik-pool
spec:
  blocks:
    - cidr: 192.168.2.100/32
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: traefik
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: core-pool
spec:
  blocks:
    - cidr: 192.168.2.101/32
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: core
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: jellyfin-pool
spec:
  blocks:
    - cidr: 192.168.2.50/32
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: jellyfin