apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:NvauqWf5haCoefa2JX3YPCVbjAn6qoufdT6omSVRsrv5l9tvYJ9swMc3ugRRGlaoHgbJzc187T7E4xdvgOKVWylnHbf8s9hdLNH6vy2UCQNwEJMDyu5oZQ==,iv:gbHc7HQfx9xWdtLqv+U0fCqJdqEeLANO2OsBpNKXkv4=,tag:bXgQyAorPPEEW4DInMvphg==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:W6eocEjw0XNmeBrjMo1zip/HfGvD3wGr1nR5K8/CSxT69z1Lu0eOKmBhKHkXbbRm,iv:wlpUTvP7x7QvQYEiAXK5w7DavzY0nqwgTWzCo0j1OXw=,tag:u7qKFk4t7X9I/QUIVQZF0w==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:CxYOSg==,iv:vM3Y8e9rsT9BNOUAtVySOjy95hYReTHXpudcoCOwRTA=,tag:fDW4TYJGdKpQh42RMaUBpA==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:Tvrk2lJyC4aX,iv:i/TyoLcK/ShVgJsfUEOePmH2DtGwRLwKkuJ4vnKZzz0=,tag:FkSmwE64I7nUbQmao7ywbg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:eZo2NR7IqRwg,iv:sWdatCGJ8wOA5I3F6MYNInOXe3w5eALjEXuZBXcQXys=,tag:pghRZfAsmWK6EqnLTRcbFw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:WGC0kOmH+/iutEmxd/byDTlZJ3VgqCM=,iv:sQ4KavXymV/P89NzFutE8gbB1p/O70Yu0rV85kBronU=,tag:oV0ZoAU7yRFbSTN/XdYD+g==,type:str]
    AUTHENTIK_HOST: ENC[AES256_GCM,data:8atrzdYjJts=,iv:0OATHBNdEDiVamLcKqt6oHK/lPAfJVOZ1gmLr2SH/qk=,tag:2L+zW7pbEu9GQJkxjIiWgg==,type:str]
    AUTHENTIK_EXTERNAL_URL: ENC[AES256_GCM,data:0iLrU14J2HgDGW15Kwa1Yg==,iv:5QDhJYvCXYnDAeyu4yLzSeQSdfKhXZ1mP1KnkWWJ7hA=,tag:Co6L5A4gVNORNlqIMx3qVg==,type:str]
    AUTHENTIK_REDIS__CACHE_TIMEOUT: ENC[AES256_GCM,data:WLAN,iv:G6EKBtSHqy/TjKSgDGjyPE3nXHe/R4BEzTwtkgaAk/A=,tag:1mAcYf5le4S9DMbn56hmNg==,type:str]
    AUTHENTIK_REDIS__CACHE_TIMEOUT_FLOWS: ENC[AES256_GCM,data:Zjst,iv:Wu1UC5E6Gwnkkrjtk0EMn2yNrIgV+SW1VsLPhuJ0lZk=,tag:DAoxNBrglmHxWhszuYi/ow==,type:str]
    AUTHENTIK_REDIS__CACHE_TIMEOUT_POLICIES: ENC[AES256_GCM,data:QNPc,iv:DxrKoicFvx/nZrEl8LQ0LR7mdSPTvJsoIKr1pZFg5Ac=,tag:FhILw6K/cJmlX0STDM8KUA==,type:str]
    AUTHENTIK_REDIS__CACHE_TIMEOUT_REPUTATION: ENC[AES256_GCM,data:HGv/,iv:wGmiHLJTFsrGPbqjFHwVvRdC3hfVLVKsSh0W83jb6cQ=,tag:p2KDFd2p9XjcYl/i6KLDtQ==,type:str]
    OMNI_CLIENT_SECRET: ENC[AES256_GCM,data:EdTTM99+2iqAAvFURKU6AoG6RgoRFSR/kFiEP38HR3x3+ANrHP3ILBYMZgI=,iv:WtPifOLrERL1+rzPh+/wvgmPCGNl+ivA5FGUMRqUj4g=,tag:7dLrDL4i8NXjU/ZfgtcJ2A==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNzNzOWpRRGFxYzlsNUNo
            eHlsTjdpNnBOdjBlUWNjSC9GSUE4Zk1kdW5VCmIzaWpmV2ZIOXV2MDI5bXEvVmpF
            QSs5OUlDMytWMDdveU9YcG0reGNYVVEKLS0tIGdUR05rc2pqZVpDVGF3NlRnRXlU
            aDRBeVJTdlVWVzRiaWpCSEtZRFQyM0kKUHF++wZHK25Sxt85tLrSrZKst0NR/VBu
            /nbIhJawLtZDm+hh1ULUvRIVVWVEhwc/kfeIobeu0/vaN8tl6h7dNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T17:51:00Z"
    mac: ENC[AES256_GCM,data:+/6muwZ4VY39lsS5QzFQvR7AUyAMxKdCgIjNNhbaoSv159Uwm+h4rxyGqFP30vTbaLSMW9XPk0S0EeZyYVFz8KMBPXrB430KC8jdjWqJfPXQkfZOB7rqkTR93U8VyXglUQ9FWbay4o9SqpgKP/PU/tJWJoh2cFjw9BZiVyPx7Ow=,iv:AGUlriEGdV9IK9BnINt/uRm5iylE2Z9XkdYBYk2kSyE=,tag:4v0wk7520crAmIWGD0+xiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
