apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:24CRE87EuBafVLcjKYwUKw5Qk3WbbdrmIDvizeWkWzU48tQ89U7VQihBOP+//FlgH88YISZ7d5E1W1gzAPDMQ2VORFWjXfD2u3OSSzF5y8WGV0ttyeMHug==,iv:XaEmSqoSdCsUPVyP5BZ0cRPCWMDmJ84g5jA0s2wDvi4=,tag:PoDKpqCzpELB0CDhutEfwA==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:iDVZ/7sPPJEb1mg51qXkyCIoh0E=,iv:SHFRlueJE82vV8s80V92jzKBqdwPQMH0RJpCQP7NHsQ=,tag:bA481ydN87MxG2ulPsyrug==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:UqJx+g==,iv:cKwuVaNtgY0zoMXiPKxSSu6xdvjBVmRO6XoCNiVub9A=,tag:9pyd3oKtZx38P4ymo6VzuA==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:UPwuEzLhyW/4,iv:c37LymQqJjpUX7cdpM2pooRhLKic3J0BCmSeWOHj3aM=,tag:U6c/JTuUV2F0LvGjq8vSuA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:fA4qIWqalBQv,iv:zNQT1Lbh/DiU5nzk6Fz3urfEidElmVI+EGCBKQkWyy4=,tag:vNSavqqUmpTV2wAyH/XwvQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:/HBEc49xF8wN35VX/e+BjNIkenXKJpU=,iv:bqbmVbyRh7kP/J07wm+kWkodKYMmIDsP1U9s4dXn8o0=,tag:20FYLDrifOVeinOUFhszpw==,type:str]
    AUTHENTIK_HOST: ENC[AES256_GCM,data:Utkn5dScj0U=,iv:YBGvmlCfK3E6wd5yXLvj5Jm4SxPyBFYnFPvJav+zWY0=,tag:W5rNn6dtEDL38U6vx7+UNg==,type:str]
    AUTHENTIK_EXTERNAL_URL: ENC[AES256_GCM,data:fZrowVr8DmtaKRpftfsmiA==,iv:xDCUsXSHbifK8boAUCWGx0MsoujmYL2ha3jg4GqH3K0=,tag:1UtEzTPnPADONI7TN5hhUQ==,type:str]
    AUTHENTIK_REDIS__CACHE_TIMEOUT: ENC[AES256_GCM,data:tXQi,iv:Pp4fetb3HT5Gi+0m7Z+8eNqtj5I8yVVfnH7aXcG0+k4=,tag:a9hawPzbWGK5fyclqNdGlQ==,type:str]
    AUTHENTIK_REDIS__CACHE_TIMEOUT_FLOWS: ENC[AES256_GCM,data:hnfY,iv:wUtTglwT8D9tLwifpwaDg09jY2GXnbqBIxwOBEIzSEU=,tag:d9XUp5laHLpLjpAxprSR8w==,type:str]
    AUTHENTIK_REDIS__CACHE_TIMEOUT_POLICIES: ENC[AES256_GCM,data:hXge,iv:SHZ7nYqJk7WtlmBd6fcF+7AeXXqLmg1aUMqJX7noxf4=,tag:r2XxjYOs/svd6J2W7MQRBA==,type:str]
    AUTHENTIK_REDIS__CACHE_TIMEOUT_REPUTATION: ENC[AES256_GCM,data:xMgm,iv:7SHat1WSc3NkYIVwQbtPgxImk9PnRChkJTeldm82INA=,tag:DqDhHFgU0Ix4PzPZQIV8Ow==,type:str]
    OMNI_CLIENT_SECRET: ENC[AES256_GCM,data:j27LQHXNKGe2XaR6kL5xtcagJoTPxWx8CQPqwKWN5fA3VDa16RS8U01HX7g=,iv:ot38H3Ujb1QXkf4/HeWUoJA6GL+m9WGu5NOhpbwHKMM=,tag:7R2WsU9hj/eV5nX7yizF7g==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWTh2Z25rVDU4Q25hUEln
            dUNOWmpHZDV5MHNTaFo3Qlhtdlc4eGYrWGlJCjJyYzZRWDhXMmwzV3ZQNDFzOFZq
            emh4RHE2dyt5VGpzQmcwSWdjY1EydFkKLS0tIGREU3BrZ0RWcFpTdVhVZWJueWZr
            N2twL3lNSlJiNEl0ZE1TOHhMRUxWNTAKrfG6uBSI/X1ow1vZeyPhhDCRhYqq9wtK
            b8jzmIDK04WyrN8J/xaA05MEPmxhMoUD0Gezgig9HXByGsbRMHtVcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T17:38:49Z"
    mac: ENC[AES256_GCM,data:1wS0e/y/SqH2RuDleVOeICH8RH5njn4lsKO2nGr4ywfy4J6yQO7KNHBfee5hpd3mqvzN4ufMaXDEhvZnGtsivawNMmRquogyEZ1mPlSI9aK24qFVgufo0TuPLqv8ytqwhEaVbwVneiclUSQd9HxczO+jDEXkcq27a+fup61JQM8=,iv:JIgShR4B1onDQl3NPk072J4oBb4CZpiBblLwwaocvPg=,tag:jeF34ZJCtFqrRWG7pVWG8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
