apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 15m
  timeout: 10m

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      prowlarr:
        containers:
          app:
            enabled: true
            image:
              repository: ghcr.io/linuxserver/prowlarr
              tag: latest
            env:
              PUID: 1000
              PGID: 1000
              TZ: Europe/Amsterdam
            ports:
              - name: http
                containerPort: 9696
                protocol: TCP
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: prowlarr
        type: ClusterIP
        ports:
          http:
            port: 9696

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: tank-configs
        globalMounts:
          - path: /config
            subPath: prowlarr
