apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-image-signatures
  annotations:
    policies.kyverno.io/title: Enforce Cosign Image Signatures
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: Audit   # start with Audit, flip to Enforce once stable
  background: true
  rules:
    - name: verify-image-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "ghcr.io/jobdouma/*"   # scope to your own images first
          mutateDigest: false
          attestors:
            - entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAElfYkbUXi4Wjb7nH76No8CgnTZNw6
                      EQNYY+5VeuPasj7FatvrsOuVpPMWxPhelHld2RlQG1Id5flgmH2P1ZRPpQ==
                      -----END PUBLIC KEY-----