apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tank-configs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-tank-configs
