# ============================================
# PersistentVolumeClaim for MEDIA namespace
# ============================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tank-configs
  namespace: media
  labels:
spec:
  accessModes:
    - ReadWriteMany

  volumeMode: Filesystem

  resources:
    requests:
      storage: 20Gi

  storageClassName: ""

  volumeName: pv-tank-configs-media