apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress-system
spec:
  chart:
    spec:
      chart: traefik
      version: 26.x
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    service:
      type: LoadBalancer # or NodePort
