creation_rules:
  # Cosign private keys
  - path_regex: '^cosign\.key(\.sops)?$'
    age: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld

  # Kubernetes Secret manifests
  - path_regex: '.*secret(\.yaml|\.yml)$'
    encrypted_regex: '^(data|stringData)$'
    age: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld

  # Full-file encrypted configs
  - path_regex: '.*config\.sops\.ya?ml$'
    age: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld

  # Runbooks
  - path_regex: '^runbooks/.*\.ya?ml$'
    age: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld

  # Any other *.sops.yaml file
  - path_regex: '.*\.sops\.ya?ml$'
    age: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld