apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
  namespace: media
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
    - name: nfs-test
      image: alpine:3.18
      command: ["sleep", "3600"]
      volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
  volumes:
    - name: config
      nfs:
        server: 192.168.2.5
        path: /mnt/tank/configs/jellyfin
        readOnly: false
    - name: media
      nfs:
        server: 192.168.2.5
        path: /mnt/tank/media
        readOnly: false
