apiVersion: v1
kind: Secret
metadata:
    name: cosign-private-key
    namespace: kyverno
type: Opaque
stringData:
    cosign.key: ENC[AES256_GCM,data:rNtfjSGwpuxe0z/ftV6zniA3yjTEzi9Jn65PnpOJxS8tV9Hij9puZx9tj3AO8SBgrQsQoC6zIL14/jC9svj89wRAR3VpZxnCcBV3I4vgm+ltqvprg7+yvXl6J7M7aMgTgFmCwA5C6b1/lgL22kmJ2lfve0lYGaBqzdtTieGdxf19HXNQ4rTv6RmJFX2v3hi5yNmyYg3iqzzLmW+7vGLd/UpsxQPgm/+ko7YXoamfCGeJ9RFmqmlSzztVzT/kHdvE0kjmHcqiUVh9iLjQW8hOqyb42Bp2HbCTecgW+m3uHOcUyQBigQq/hxQdWB79lvlGgQUyyx67GyWyp4FfS7bQ7Eq5t7RHraqVU5BNN4gVcyWCnsdLVb/NSNbn4yakB4XQ7HkEzRLGZfIn4ULiy2wuTB4wW5LSADuLITynsgUSgYFQtNPT2akCr8lvpd6Y9hkf0+Dy1MfThhYOT7HKssxMbKW+XkrCArwBLPlrMRai32s18cMZYlbyrWrCmOtoeZeUjSbFO7IRq2FUVQEMfG+o//Er0JIX/2B1zeQH+KSrGr/rh/piVqoWEJaPJiDeqhExz8dd5aGxoLUHiRp844HHmflah590lCoEU0qzdTN9jZSE1MHfpy072SOhTrqZakUM/7VmIO5cfwSrOrcls3rgSQ5mhGu3YEmCTfSSaZIJrjSVvW5TD1ZidQsrkVAO/6+C/TzmLdLjHVxbS6rsFNISjDupSCAVHYXwBBxqemve7J0bgglUtPuXiBRIK+D2AqSeH9iKbyzHiuoswD695vl813CldnwBUXVTXw62jfQ/ChwjwgIg4tz3/Mi4r94NMZ3J8BEC2rwuqt1SdKs64oG9NjMphxYbir5OX+/lziY=,iv:dPmUVjSi9VYI4T2HSPwywsrAJUvtXX72UZ220MKnqJU=,tag:p4RGjoDfw2eUUG4EiXONQQ==,type:str]
    cosign.password: ENC[AES256_GCM,data:MORVOIl4WVMQZBXomik=,iv:gCoI7bp1x0CCA2B4l57Z1baLNvnOqlYtbR4EZxCj7QM=,tag:L7jcewqJ7Mtp8iH0TrEYPw==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZzhvTERvamdOOVQwb0Rj
            SHk2VjZyZkFBVkRRWHlDNFMyWnVxS09YV2prCmJDYWUxSm1xWlllSVkyQUJrZk0v
            a3dQR043K3RjRnZnZDQwQ3JFS2M4WjAKLS0tIDl3Vm1paFNCVmx0WWo5Ump4bGpP
            MkE3OG03L2hFdFphS1ZwN010S25oOWcK/sByW6ioLKGz7GBAYuUu1uOHzDpLqjUe
            8rcBk2OVE1NIJzQltZY2V8bd7sUNwPDF9s+CVzb7ouXRWkEL0a8O1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T13:18:14Z"
    mac: ENC[AES256_GCM,data:AmMGtGlxe+KrCnc1qo7tiX8nGxCptEDSo/nJbk4y722pxweGFSFXecFIEi1s1NG8MfDAoFmjagSHZ+ZklpcneYpkCDixymCJ6SCENkTx9+Siv8F16L99LBve5KY6k1jbYPtY3P30imVITBQ6qA6xHhgfPc8Dz26Md8J8KHaVVQo=,iv:CneCdvNG0teKIr27axlWrVCm9G4RduNdQjV38+wm1vY=,tag:kdg66uSgWFKgVLYY1joIfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
