apiVersion: v1
kind: Secret
metadata:
    name: cosign-private-key
    namespace: kyverno
type: Opaque
stringData:
    cosign.key: ENC[AES256_GCM,data:B18kynlExFyilZNXC+rdSELLpT120gutlDA1d7f75HNU+2vkWHNYKFEtL4d7xqvNH/Fu0uDJydMHJ4WsrjyUOixTTYnV50Q2/NwwLRs/KFKO8UD0tMpwvDBJx1Vhp0e17FVlSHKO0i6kQdtqbcc6AlpSDU4wdHMf6P9fylqlfH6mPgO63NmU0Crj/Xaybl3dUiWC3y2+XEMR1QW10Ret/mA4TFyvj1CH/B2OtLmUVtKpBiAKcbz32ZJckExKSm3G/ri4gXz/FVA5X9canJgW35G5WV83/GIWJRt5VNheNIW3FOKsPsQT/KQ3YURSclM6DAe0qJeugEvD3wwGSc5izxc+ap/GyfQbT2FVOsrzHmSODxDJ3u3KNf0xBJNQviFpDZFsc+YYBBYd2iBGl86HSDCm1LB7p8wJoizUOwMmoStvjVj5ILftYd4Wj3GJyWvRo+NGX5Ov7RBBAyhD5uaxewXd1LUf26iksIKLwmPglCtdePDfEqoBQgLFvdcINHMEU9Tvr+YyJwoWQbFB4Sbjd6Zv0mbqdOk4TSnJbBODxRIXy+yU0giYAjOyTEFvvFqZW6NNI6n0ltNSKa/b0DMaVPucmc/frQCNpgHIk7k5HTsS2+nvpbBpQHongIpf0qsNsD2u02xyuklM4S5C2m4ySgh4mFJ1fIiamGEUgPJvJA0o7zLPeOaDCcM6ag1IRE/PKEsTlY7elffT4uuMgdRgmbiQigGF1+yEXY57oHzHeGUbEbb5EgwkVnOngCGpLMtdq7kmhqz78o1DD5RiljEdO49IJ2gU89szBApP34ol0Sh0RtBF1bDZm1y0JUpaBp3DE7gGoYtKqQB/K6pa5b1FRFMXU28dP1gKGXK243s=,iv:Uhdu+NjMuoP3cbevKvbcuUcdEvjPKbY7ioL+CO6R6YE=,tag:EexKd4fDCXkuro12h3tfTA==,type:str]
    cosign.password: ENC[AES256_GCM,data:KEAnMBLEpC8F+2cI33Q=,iv:4hvJ4uqIFn7yX54pdvr91glVUDVajbcTL/hlU/Fmepw=,tag:yOsfkssVBFE1jxEZ3VZSLA==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubGFVRUV3K3IzQi84S0ZO
            MDRNVE9ObDFqb2NCUG5lOVIvUldTdEZvMndVCnBtUTR4enVHbGtaUHdhVTJzb2V0
            SlpPR0U3UFJuKzFwbEtrNkhhd3RrYzgKLS0tIHhKdEJJYzVpQmpoRVhrVmJNOUxK
            Nm91dkFmSkRZL0hPNU9pakdkcnBTUUkK8ksUO0ex3NvqzQzJ6/n3IgRlpLkmNoNY
            ynRnXasBtTb4LOr8lbCOnlOB8Ym73gvXKslTfI96E7p0sp7+c+6shA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T21:23:23Z"
    mac: ENC[AES256_GCM,data:R6yCxoiRqQComcDPKjB5goh2+R7NWa+K5ZNHyOjxSQwJCkIeQmf/cb5cKGLz8xHDnQFZFRmp8nd55koV5JwfTTR4emV+JiIyPoPs+/bO40yZ9QldGlt76nZLlJOebN+Sh4X0hacshrnLWxHuIGYY3CuluUrJxLFAbuhWD0WegYU=,iv:25+VC25Z+YnbuEQbunMXm6Etb2KHN/ThxYwJQWtIBdk=,tag:OY9geB4Popr+iR2WKM3GNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
