apiVersion: v1
kind: Secret
metadata:
    name: freshrss-secret
    namespace: freshrss
type: Opaque
stringData:
    FRESHRSS_ADMIN_PASSWORD: ENC[AES256_GCM,data:i4dYVePt96tIToya,iv:pKOjvu5ZlRiBobRXx3UeCF6bgduWS7NibPGaJpUry2c=,tag:jmizbXMMDMLF3RZFRKNWmA==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TUtTMkJDais0d3NpektK
            cUJRUWo1d2R3eG1MTzEvR09id2tmcHhJK2dJCnhJTm95NWY3aHp5T1Y1akR6YWgz
            azZUTDNjYThvNHdQUjRwYmMzN3NWcTAKLS0tIHJrVXJ4Qk00enZieHJDRGNjcndL
            d0NoMzJkaDlYZjdicDZsMFMyWlJOL0kKVe9YtCwBZOjf8dPIVV4xiSPBnHQeVN6V
            nxf5C9gQmh1o9V2XRkzZrrR/GFIygVPFwwx60VS+GDcYbXE3p2Mrfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T14:36:51Z"
    mac: ENC[AES256_GCM,data:1RjPIbUjwDG0R/pC5aUqmYONziiOcGQGp8OTTqYWAlSdxVkKGIlrpp4FJ0cF4AOwd2OHOxwJXV9o2QU7fjBNK/LpLKMMCBSFzA2Qt1l4QchnpBSfqyPc4OZvr1QGyFRo1AfuTI1QFZQWqJRtcH5Umkq9i8dBNzFK+EMv8Awz3+4=,iv:XF90O4GUfOMT+9p+IXTrVLqa+/QTIdl+DVcb33bXlpI=,tag:EKFwOA82d95epwSBk8OKlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
