apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-secret
    namespace: headlamp
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:kvj7q4syHAciL4SxczV8WzAP1AcdZOnu8sYNEFy/vX5S7TWY8Vrrmw==,iv:N70JzoRvRxbMN73xSmgq0lk4RQerVgSuTW+cshzK2tw=,tag:jhhhN8PDruKEq5GtTVX7sQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:FqfL5L98qCOPMPhJAypFY/YbcmZj3k4r1zJxDox8J79tdHi/tQGq8czbeCD43bd+wrrFSdhaLU0uRqEbOsJ9G1T38uAe+JSilT5a7URGcJQCbJ/4wzhwidusomCXJij7NvAOEvp490AKeJ8504Vgz/JLfPKW7vhxKIlO+e9YRWY=,iv:syqGiDiK+sdYuO3RUVNEuqKUFU400ubTlyDDARiAl4U=,tag:XFCc3+/oGCiuqHvmm5nILw==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL3RhT1RWRlhqeERpNGFk
            SGZ1aHM2c1FJc09BTGxEQ1k0RkVjd3pPdURnCjB2dWVQbmFwS3JpV0FDenNhc3BN
            elJJYnBkZ1VRK1NJNnFZNW5DQm51RXMKLS0tIHJ5L2F6ZmZsRFFMeFA3bmF0M1VR
            TS85ZEx5TmhYaDU3UmI2Z1Q4Wm8ydmsKpf1ABVu5VUrQr6oigAc4FjrNl8/8dtvz
            QfKKbqIrRAcKv0KSV+5hX2GIY9jS1xlH5Nt07SZOEZfI+FSAJU0vtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T13:24:37Z"
    mac: ENC[AES256_GCM,data:tWkCVSezqRbDK5oSfjmgTJzVC+V9TOmOjVuY+UE+oSF+0LOyjMLID8rzV7x29jwONUCNyZykwAGp2GQdxsYVM5XBxs+lNseUNf40PVCVIWEVfK6NziSldZHTdl5YfgPFomT50IDQSjHYGtnXSXO0kwBW0L5cH6wWpM9TzeGgMWM=,iv:PqebPap59jbvazuuL9jxyVHhwixVeP9S2dZynMVBOKQ=,tag:id0z/IzVMAER5hQOShf9kA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
