apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-credentials
    namespace: headlamp
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:sOXQ64JwfCHu4qRiOji5xEPeJ9Dcp9YzUQKsovhquXGA8RzyaBxFXA==,iv:fU78ZrQcPS2XPz7qQ8Y7HZfOqpvmkSw9Iu+YQltQMkk=,tag:Uu95tSroxtrXjblcVU8S6w==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Nw+nZNk3ufC0Seh9ULGJi2J7nIeVZ/HrpJDU2fnjU++8DjcvMWo8ZEokxW3Ts4NAVKUdDSwBA4xZE75Xu0pzHv0AISY19LByrQluHMMikvv0KVCz1Aqphil66tgptjzSZL5lIcepbfdvao2zVlj+nBgQUebBdZV5VGr5AXCSv1s=,iv:ZnfRN7gXBcighpTAd3KJuFGMVA4kjusyBbIRBowM6PU=,tag:9g87tYppw2q+AV1DhfoljA==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:BfyWAb76QekzxDS6fZMOA3S2GtJNSvRJAO4mrxr/4h+KEXTMZbfQ,iv:jX1kJB3j9kPF1zcLhzR5EBqW36JEl8AMLKvJ7S+PS7Q=,tag:nunpCJFjMVdrtwXdxSnkxg==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:L3D7sDNq6jGDy6dYHe5EXPLdvrGQqZSIlMl9ZpNlefR7pXw=,iv:Mikokyva9uGU+PKp0Bri+nIksNImZ06LQvzOrx5Zj7s=,tag:tbaOz7/j4mgrMh057JXUYg==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSGU3YlRSQTI3NWs3L0hM
            eTBuMEdaQUFBdTFvRkFlaU5Sd3pxR2tJZFRZCmlBeVhvVUxsRHBPcXdvSVRLOWxx
            Z2FDcDczYUFxYVZQUllnN1JTQlNJOHMKLS0tIFBwZzJrWEZ3YUhxaWhBdERvcHR1
            UkxuQ0tFVTFDYXc1aStndXdmazdaSVUKdN63qnEFHkAXCapGuBFUUxKPSdFV/OcJ
            L3hsYWEK9zfHZDqKymUMHJxp20U7I4nOc1MM8bkfXNqWWDvEuAsWYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T16:32:31Z"
    mac: ENC[AES256_GCM,data:i7JFxJgjbKRGACq+FCHEcpDiR0arRKEbGYfSQFF241k6AV4t2fU6K7znIvjvvaT5slz74d88JwQUaaLqxc+UpNjEvLxUf+kP14M189xe/6qemIDti8Cte82jUuRn9Qee1Wo/FX1uXo80h/zd4DI//IuoREVmQ5XpjCTQ81RmcVM=,iv:8fEWr7PkuwH/LKrUsm7b8HvXsLTEjPR6P7r3wEwZcfM=,tag:tBXv5p7O6V4zkt2n8oHtdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
