apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-credentials
    namespace: headlamp
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:yy87vD43YvsXJ40w0Wx/8yZV2twwbvlIOotZf9zBcgXogh/Fyjt2rw==,iv:+K8W7YUIJ0Bg/zmJmHcC3951l0d0862jQ8kv/IiHi3g=,tag:AJ0T+viyu9/kmaRADB4aXg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:w5KbDY1td045ApSDaFhkkfv9Ah4SC0Llq2RYm3dCtGDxRf1ss6R/Yp8rRE7A6KgiJwtZ0+hwshDHs/NeTjlj2qcYr/4IYQSkDBGPojZl7kPGNkvYvE1jbCFpul6pMzqYOor5zB4RMpdaZH5V7lQtD4g2Uaew3iCZYlDarE0M42U=,iv:FhLB8OJn3I1RfBVV5zTQvONKnIeXnQHlFnNQJvyeoD0=,tag:WcdT0PPonGNAFp/8k/pkIQ==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:W5zMgfgcA8JZgof2Wid6sZkznkZCZGtlHkAMfC1QmTiAYV18ZrCkxw==,iv:j2eRc0jRazu1uTW/RlyOco0RzQfNFvv1s0LMSBVmTXI=,tag:L7SIZYZCeY6WCZ3M8tHM0Q==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:WF1sEX7dxGV9uE9BdP4KcnIJMZ0=,iv:d8AAzy92uVLtlN+HdxKM8VDz7Q+k76doFphvz0BLL28=,tag:OxSOqK3Zu7TkDWwrRmwVLQ==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVnhJTnlmMmJEbndlYXJn
            TnQwYmprWVRWc1UxUFk1WUhYS25IWGs4dUM4ClJLNkNUMlYwaytKbjlYSkwwbHN0
            aHRQSWI3SjllUGlSMzlkU0NnRTZETjgKLS0tIDJ0enZaWkJtcWFvRzlzMGE3dXhT
            cC9Lc2E4ZTFmNVN2VXhPNHFreXp2bVUK/5vX4oJUzvEzKCLVRbepE/gYoUxa0KYi
            Ghyugpp520HJMkjaBfbiuZXhJppYjU79u+f8MQnS5X0a++24OSpeGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T22:14:00Z"
    mac: ENC[AES256_GCM,data:/bknD+iHyuyyFdeHGU6K/KOFXQTFyHZEFO+m5AUz8TUqr63UG9YARvyLdz0upVojFHXfOIalc/FiwHikTIz1aVyvgPlwt/pwO+svsVDcWtA/nUqFIdleg1FJGzG9OKs+k1a72UiqUzl/h7NbN+XURSdRcsOEZSCSqOGKYB1VNK0=,iv:sF0vYaBM9n0AQdDNGwVfu9jZDSgwUxaZDBJBM+6O3uQ=,tag:L7qceYrBlHTTuQWrE+RgOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
