apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-prometheus
  namespace: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      prometheus: kube-prometheus-stack-prometheus