apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/qbittorrent
              tag: latest
            env:
              PUID: 1000
              PGID: 1000
              TZ: Europe/Amsterdam
              WEBUI_PORT: 8080
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: 1
                memory: 2Gi

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: 8080

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: tank-configs
        globalMounts:
          - path: /config
            subPath: qbittorrent

      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /media

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
