apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-webui
    namespace: media
type: Opaque
stringData:
    QBITTORRENT__WEBUI__USERNAME: ENC[AES256_GCM,data:SIjrWfU=,iv:OSOrAoCet+9Pr/tewi1IIrNN5caIVlYD3WiuIEMOAlg=,tag:MJORzNe/zobBLITcXiW50Q==,type:str]
    QBITTORRENT__WEBUI__PASSWORD: ENC[AES256_GCM,data:rc9AOwzirp2g7ulEJera2SxPaZMU,iv:DdLQYEww1gpFJIQMX1eX0Iq1K7glKSkLTlFiHrmWU0c=,tag:8U++xF+ofrxGnBSOfh3DBw==,type:str]
    QBITTORRENT_USER: ENC[AES256_GCM,data:SHzFbO0=,iv:JtlqqCKB7C0EpenBeOReym4/+oDYrRjW/iuORE6Fkow=,tag:xaA0pXUExlwdoP6uZ93g/g==,type:str]
    QBITTORRENT_PASS: ENC[AES256_GCM,data:sFXeRjzyh2mUg8JdhiEcWdImLewb,iv:wHaJrx6L9OFJyl0BUyDL8xcEsB4bpHxf3M2srEo6hWU=,tag:/Aijm9FUllhpVHo9mmbDUA==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTEJlaytId0pqeDE0WG1u
            R2owOHpGTUFqeWRKTlNTMFZPZWo5WEd2UmhJClA4bjdURnF5ekxkZzRPblkwak9X
            RFhjWjFkZjl4bGZGdkpxcE9JaUlNU2MKLS0tIDlIVXBjOGc2UVEyS2hzdWFxWklo
            WXNQcXhLV2lNMXM3UU41L1JKSXBVbjAKyjYJPlm4LwS/+kZgX0PqA3l05UIgEPxK
            sedG2yMH3BR5bm65fH9qmE2KfTMqEpUTRvg+J9ZgNGZe3BGXfn95yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T16:18:14Z"
    mac: ENC[AES256_GCM,data:cTzpXGzsYbnhcXvxwHh4GEafF1Y5nMJqQ+nQErRGM7R91RCXpeF48FlS8d2AaMOzqFCUwusGQdFuRF7PnO0JJ5kI29SiunM9sLEn5LtT3421+vUT2ZxMm289ItZASYQZMAZ+qnDgUIaSr911yOOy3DmQHFpWFl3aYH1tt43Nq5g=,iv:GQE2PLyLPmrmsd0QsHtUb8rz3apyKTqtPIpfbdffsqM=,tag:oe0X1kDn0WwKtPJWfDviyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
