apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-webui
  namespace: media
type: Opaque
stringData:
  QBITTORRENT__WEBUI__USERNAME: admin
  QBITTORRENT__WEBUI__PASSWORD: super-secret-password
