apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-webui
    namespace: media
type: Opaque
stringData:
    QBITTORRENT_USER: ENC[AES256_GCM,data:rl6+,iv:kUAPccXWqX4SSQ5AKsjFWowe9TpCvtjKATjpeSrzLOE=,tag:I6tt8mYy8WDoL5eEanzDYQ==,type:str]
    QBITTORRENT_PASS: ENC[AES256_GCM,data:Dzj0twUwyDyWJuQK,iv:1gyZwJBHrOEk7P24VWKLcmEdgyzBCt/7Z4RPlCdI4Zk=,tag:7xozRkr6Db7aJYPe6WITrw==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTEJlaytId0pqeDE0WG1u
            R2owOHpGTUFqeWRKTlNTMFZPZWo5WEd2UmhJClA4bjdURnF5ekxkZzRPblkwak9X
            RFhjWjFkZjl4bGZGdkpxcE9JaUlNU2MKLS0tIDlIVXBjOGc2UVEyS2hzdWFxWklo
            WXNQcXhLV2lNMXM3UU41L1JKSXBVbjAKyjYJPlm4LwS/+kZgX0PqA3l05UIgEPxK
            sedG2yMH3BR5bm65fH9qmE2KfTMqEpUTRvg+J9ZgNGZe3BGXfn95yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T19:45:29Z"
    mac: ENC[AES256_GCM,data:c4BLM4bIcUuqcSlQH329W1F1PGjCl1sTxcSE+KrEb8/zV8UlhCE52y5rMJe71jpkLaqensiu0bsAK60KX+Yyi/MdH6jJEv4Gc+lC1RnN4IpkKqe92CEdOQ288S3tOPyoJsg8d0IpUDGEkMzSvEqKIOn0tPXgxBv/0Ul5VFzIDI8=,iv:/arRToXkyb0Ikag6f5IGlbXYeFCDNjZgSXAxqP+BnAU=,tag:8ab3HOrEw31FLoMZGSLGkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
