apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: joplin-tls
  namespace: joplin
spec:
  secretName: joplin-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - joplin.lan
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
    group: cert-manager.io