apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: joplin
  namespace: joplin
spec:
  interval: 15m
  timeout: 10m

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      strategy: uninstall
      retries: 3

  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      joplin:
        containers:
          app:
            image:
              repository: joplin/server
              tag: 3.6.1@sha256:95c1badac330e53918ff3a756fccc67d1d7f65d00a4f806c6a5f79925e7f18ca

            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi

            ports:
              - name: http
                containerPort: 22300
                protocol: TCP

            env:
              APP_BASE_URL: https://joplin.lan
              APP_PORT: "22300"
              APP_LISTEN_ADDRESS: 0.0.0.0

              DB_CLIENT: pg
              POSTGRES_HOST: joplin-postgres
              POSTGRES_PORT: "5432"

              SIGNUP_ENABLED: "0" # make 1 if we need to register a new admin account

              PM2_HOME: /home/joplin/.pm2

              TZ: Europe/Amsterdam
              PUID: 1000
              PGID: 1000

            envFrom:
              - secretRef:
                  name: joplin-secret

    service:
      app:
        controller: joplin
        type: ClusterIP
        ports:
          http:
            port: 22300
            targetPort: http

    persistence:
      pm2:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: local-path

        advancedMounts:
          joplin:
            app:
              - path: /home/joplin/.pm2

      logs:
        enabled: true
        type: emptyDir
        advancedMounts:
          joplin:
            app:
              - path: /home/joplin/packages/server/logs
