apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: joplin-postgres
  namespace: joplin
spec:
  interval: 15m
  timeout: 10m

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      strategy: uninstall
      retries: 3

  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        runAsNonRoot: false
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      postgres:
        strategy: Recreate
        containers:
          app:
            image:
              repository: postgres
              tag: "18@sha256:ddbc320a9ad558c01c719248108e607eadde92fea799fec799028cfb2fab7319"
              pullPolicy: IfNotPresent

            envFrom:
              - secretRef:
                  name: joplin-secret

            env:
              PGDATA: /var/lib/postgresql/data/pgdata

              # Proper secure initialization
              POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
              # Ensure postgres listens on pod network
              POSTGRES_HOST: 0.0.0.0

              TZ: Europe/Amsterdam

            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

            probes:

              startup:
                enabled: true
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - pg_isready -U "$POSTGRES_USER"
                  failureThreshold: 30
                  periodSeconds: 5

              readiness:
                enabled: true
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - pg_isready -U "$POSTGRES_USER"

              liveness:
                enabled: true
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - pg_isready -U "$POSTGRES_USER"

    service:
      postgres:
        controller: postgres
        type: ClusterIP
        ports:
          db:
            port: 5432
            targetPort: 5432

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: longhorn

        advancedMounts:
          postgres:
            app:
              - path: /var/lib/postgresql/data

        
        # type: persistentVolumeClaim
        # existingClaim: joplin-postgres-config
        # globalMounts:
        #   - path: /var/lib/postgresql/data
