apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: joplin
  namespace: joplin
spec:
  entryPoints:
    - web

  routes:
    - match: Host(`joplin.lan`)
      kind: Rule
      services:
        - name: joplin
          port: 22300
