apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin-app-config
  namespace: joplin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin-postgres-config
  namespace: joplin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 10Gi
