apiVersion: v1
kind: Secret
metadata:
  name: joplin-secret
  namespace: joplin
type: Opaque
stringData:
  POSTGRES_DB: joplindb
  POSTGRES_USER: joplin
  POSTGRES_PASSWORD: joplinpassword
  APP_BASE_URL: http://joplin.lan
