apiVersion: v1
kind: Secret
metadata:
    name: joplin-secret
    namespace: joplin
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:cZA1orZB,iv:9HXhrWrhiVpFZRWz299DSFsCIcUHGkTRrzbIWEXYKaA=,tag:uh37o8Hs1HjkzPAJlJ76yg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:/D5cAOzN,iv:j1NNihI00igWx4Wers53qBpBJFbwK953068d74aUhV8=,tag:hCXCbAPKadntDtJqXoPetw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:MaMgXbZ5QArguixpxEg=,iv:u6PYvEu9ejqKuQM5JCTp4UAXhi/QF1+2PJceKoaOWME=,tag:PWPa0WdxhDvJiyI9ZAuNcw==,type:str]
    APP_BASE_URL: ENC[AES256_GCM,data:D78MBMawrtkjOGyX0viD2Wk=,iv:ojn/2bQ9qYb7k2GN+cOu+KSkdGMtgsTjAk+poJuuKi8=,tag:l0/wclww+WHFs6M3Mw+F6g==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:hnSkQZ0QPX1GYSVqpewNNNKEWro=,iv:Z4bv0twKS95Qb0aUFVxYZwRCnSO5cRZmx47tlnsKFu4=,tag:9Cum7lJZUbGMaFc3Jy2weg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:55oxe/LaUAJ4sqq/r4gk,iv:JQccroW7Htb6dAyjfrVndhn1YCOSBMHJsOwFE199syw=,tag:bxhV1FXW8PYceL490SK1sA==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdWg2bGk1T2ZOd2hUT0RK
            RlBFeExoRG1oZlpMYmVTTU1nb0JGekFXb1JNCkQ2bStSRkxkV3NPOVoxb0ZwQkZT
            VVY0UHFucnB6VTF0OW4xUXhZUVgwUjAKLS0tIFNKYW56aG5NS1hsbS84UnFMaHlM
            MHA5YWtHbFNXU1NaZ0J4RzF1M1FNOWMKFAacprcm+Y8m0zrqZiFpYqmfCNDKDDD6
            MHrxmp1k4oM1mfQEebYlkvd4iaztMTm7hzfCX95ZlcNY4jdEH9h2wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T14:30:31Z"
    mac: ENC[AES256_GCM,data:w34hYu4VjDibVzjo+ti596YaCjgpvSmdwiHkRWBREitj2aBT6RAcozuIO8DzqQM4jWUOMB/7lH5JqzLyUhOeEMDbkWvGYXPPz6isWRyUF0UH8oRlkN5GRom+JfFzofVUp0ny9Mvp+XMz4/sQ8qNikEca7hNqp4ZMZ2aMZCi9o3E=,iv:I4sfl1RQ9WZQIlt6Yq0rB3qZFgLX5Rhv7LU6vvghAgQ=,tag:Fq8KSjNBCmDvuPPeXrW91A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
