apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: dns
data:
  config.yml: |
    upstreams:
      groups:
        default:
          - https://1.1.1.1/dns-query
          - https://9.9.9.9/dns-query
          - https://8.8.8.8/dns-query
      timeout: 2s
      strategy: parallel_best

    blocking:
      blackLists:
        ads:
          - https://oisd.nl/downloads/full
          - https://adaway.org/hosts.txt
          - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
          - https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/pro.txt
          - https://raw.githubusercontent.com/badmojr/1Hosts/main/Pro/hosts.txt
        malware:
          - https://urlhaus.abuse.ch/downloads/hostfile/
          - https://phishing.army/download/phishing_army_blocklist_extended.txt
          - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/tif.txt
          - https://raw.githubusercontent.com/elliotwutingfeng/GlobalAntiScamOrg-blocklist/main/global-anti-scam-org-scam-urls-pihole.txt
        tracking:
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/native.apple.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/native.samsung.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/native.tiktok.txt
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/native.winoffice.txt

      whiteLists:
        ads:
          - |
            clients4.google.com
            clients2.google.com
            s.youtube.com
            time.windows.com
            controlplane.tailscale.com
            login.tailscale.com
            log.tailscale.io

      clientGroupsBlock:
        default:
          - ads
          - malware
          - tracking

      blockType: zeroIp
      blockTTL: 10s

      loading:
        refreshPeriod: 4h
        downloads:
          timeout: 60s
          attempts: 5
          cooldown: 10s

    caching:
      minTime: 5m
      maxTime: 12h
      maxItemsCount: 0
      prefetching: true
      prefetchExpires: 2h
      prefetchThreshold: 5

    redis:
      address: redis-blocky:6379
      database: 0
      required: false

    ports:
      dns: 53
      http: 4000

    queryLog:
      type: console
      logRetentionDays: 7

    log:
      level: info
      privacy: false

    prometheus:
      enable: true
      path: /metrics

    customDNS:
      filterUnmappedTypes: true
      mapping:
        "*.lan": 192.168.2.100

        truenas.lan: 192.168.2.5
        router.lan: 192.168.2.254
        omni.lan: 192.168.2.12