apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: dns
spec:
  interval: 15m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: uninstall
      retries: 3


  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        replicas: 1

        pod:
          dnsPolicy: ClusterFirst
          nodeSelector:
            kubernetes.io/hostname: talos-cp-1
          annotations:
            configmap.reloader.stakater.com/reload: "blocky-config"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault

        containers:
          main:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.26
            args:
              - --config
              - /app/config.yml

            ports:
              - name: dns-udp
                containerPort: 53
                protocol: UDP
              - name: dns-tcp
                containerPort: 53
                protocol: TCP
              - name: http
                containerPort: 4000
                protocol: TCP

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_BIND_SERVICE

    service:
      main:
        controller: main
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 192.168.2.53
        annotations:
          metallb.universe.tf/address-pool: dns-pool
        ports:
          dns-udp:
            port: 53
            protocol: UDP
            targetPort: dns-udp
          dns-tcp:
            port: 53
            protocol: TCP
            targetPort: dns-tcp
          http:
            port: 4000
            protocol: TCP
            targetPort: http

    persistence:
      config:
        enabled: true
        type: configMap
        name: blocky-config
        globalMounts:
          - path: /app/config.yml
            subPath: config.yml
            readOnly: true
