apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: dns
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: blocky
        namespace: flux-system

  values:
    controller:
      replicas: 1

    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: latest

    service:
      enabled: true
      type: ClusterIP
      ports:
        dns:
          enabled: true
          port: 53
          protocol: UDP
        dns-tcp:
          enabled: true
          port: 53
          protocol: TCP
        http:
          enabled: true
          port: 4000
          protocol: TCP

    persistence:
      config:
        enabled: true
        type: configMap
        name: blocky-config
        globalMounts:
          - path: /app/config.yml
            subPath: config.yml

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi
