apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blocky
  namespace: dns
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dns
  selector:
    matchLabels:
      app.kubernetes.io/name: blocky
  endpoints:
    - port: http
      path: /metrics
      interval: 90s