apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  maxHistory: 2
  interval: 15m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: traefik
      version: "39.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system

  values:
    deployment:
      replicas: 2

    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik

    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.2.100
      annotations:
        metallb.universe.tf/address-pool: traefik-pool
      
      #Traefik will be reachable only via: 192.168.2.100:80 & 192.168.2.100:443 :)
      spec:
        externalTrafficPolicy: Local
        allocateLoadBalancerNodePorts: false

    ports:
      web:
        port: 80
        protocol: TCP
        nodePort: null
        expose:
          enabled: true
          port: 80
      websecure:
        port: 443
        protocol: TCP
        nodePort: null
        expose:
          enabled: true
          port: 443

    providers:
      kubernetesIngress:
        enabled: true
        namespaces: []   # required for chart 27.x

      kubernetesCRD:
        enabled: true

    additionalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik"
      # Enable dashboard
      - "--api.dashboard=true"
      - "--api=true"

      # Enable access logs
      - "--accesslog=true"
      - "--accesslog.format=json"

      # Trust internal forwarded headers
      - "--entrypoints.web.forwardedHeaders.insecure=true"
      - "--entrypoints.websecure.forwardedHeaders.insecure=true"

      # Explicit entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

    logs:
      general:
        level: INFO
      access:
        enabled: true
