apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:rDon4PTmRInigOyp05UpEDgEVlPYMUg6G+6XpleWeCxkgR7siydC8NBZTxCoayOAzKkSHJjpNavCC3wfp7D6qQ==,iv:bmnRiterJDSRrwX7oOxuc9YxKI9YLb81pEczfauWCmg=,tag:GiupYGGqaWg6vQjFM8vx7Q==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZXdJSytYT25XYkR4bWRx
            MDFicDNaR1VndXJXM2N5SGhCNXdBVit1MWgwCjJwbjNsUFV1NlZZbUhyMktaRkdW
            c0JoVFJ5bXlsRzhOZ1dlOEJyWVYyVEUKLS0tIFJzdGt4NVdUWENVYkI0NENmZWpx
            a01EUkt5MFpQVERqdFRpM3dZKzRXcncKR1EmS7tUKwOtdEObmjlqRalCz/sj6Mpi
            NWL+rrvZbvrrvQ6Em+54ct2agJp6qO3MABhfQ7t8MW4mY1GgZdlRsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T14:09:39Z"
    mac: ENC[AES256_GCM,data:ftrUL4N9b5EOVw8uJDEHQnbBqqt1OQmhyXrktaqgJRsr/HPcPgwr0a58Xegu4nP3ejKpioXU6eXGbzMh1Zi3sPL0ujaSxnkdI7IV8alWKEJh3/oxw6wD6550Xj3pHww7uBSgTQ7rzY8tYxOik+4H8ZWnd218MvBDzhv0Kd5A+Ec=,iv:awIoraeL7kTdq16tq6HAsVoZGDvbqEXpYZyFVbEZ+xQ=,tag:jPzTHUA+fYPqK0hVwP7Erg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
