apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.lan`)
      kind: Rule
      middlewares:
        - name: traefik-chain-noauth
          namespace: networking
      services:
        - name: victoria-metrics-k8s-stack-grafana   # ← fixed
          port: 80                                   # ← or the correct port
  tls:
    secretName: grafana-tls