apiVersion: v1
kind: Secret
metadata:
    name: velero-minio-credentials
    namespace: velero
stringData:
    access-key: ENC[AES256_GCM,data:zgdHOL/cGhKHSxjQWpr6xewLkvA=,iv:d7wRMdvvFzK4ehBybwF//AMlv6HtcuSRJ8dOGcpZm7Q=,tag:cGFgLU7QnaEJoPuCSDPkFA==,type:str]
    secret-key: ENC[AES256_GCM,data:BSmOQBhY4mjY3AX1r3Y8mh5wHgi9ZkBBi1aLqLYb2bcOuD+yVSid5A==,iv:yK6FVcmWuH/UC4YLMVtovQQFXhbM9ijnhJPO7ZJ2JTQ=,tag:a3u9XXizrim/3WMkjYgDeA==,type:str]
    cloud: ENC[AES256_GCM,data:KlaFnZyUhdSTbuWvVxKGdIoBYqXix8yGUJbrFjZjRP7yu7VfQ60Wtm3UjMfThDsbzsE0S5v2qY7UeX/dfeL7/b++ciHqBX95UGXnOrySyjlvc9viXy+/QAmmvpnT+9uI4CYEzcpsjh+6wwlu7BlN3N1oZnw=,iv:iYgoXaQ3r2zbik41moBlvlGJO7HNFsk31Mwl4hS/Syg=,tag:ziCUTdeVzlmUcqYHZ5foGQ==,type:str]
# both aws_access_key_id and access-key must be the same value (and same for the secret). 
# They're two representations of the same credential:
# - one for MinIO to authenticate with
# - one for Velero to authenticate as a client.
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRG1XNE9OZDhrN1p2ckRU
            TzBsSWNwS3c5cklmc0VGa3hEYVlKeEw5YzNJCmtqN3ltSjYyaUxmenM1eHY0NHlF
            dGtmSDRwR1lXR2UzQWtRTXlUWUlhNHMKLS0tIHE4bVlzZ3E0RDhsazQrK0F5b3JP
            TTdwNEhNNHRQTk0yVmZNKzRRSGdib1UKaf/PbqREfW3vFxhVqL9Y+HQfP1mIhxfi
            C+M24NFWuJCx6eSy9LLvznQ+NSCTAVmBWeVnP8T39X+1yREea29PeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T09:55:10Z"
    mac: ENC[AES256_GCM,data:N5HcPMTKToUPaFbR0rMCfkZFaI+7S5hwzOLGFfaxmcGK17mI07ewHsa3pBoquq62ba4A3FuG4koELaImyKeiUu9equiJvo5kGXoEVYlfYrTSc4D3Fl0yYTEUYUqI9iyHGx6VfFdognXfoO0OFZP4/j2Zm0Qd1riDUr3t8wi1TQM=,iv:cMJYp6Nvhaae7GID1n5tbdIWiJcxEbdMxDCOriYGPjY=,tag:nNYNhpHYUbRreilJ4trfgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
