apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-backup-storage
  namespace: velero
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 500Gi