apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-gotify-config
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:K1DiVCDE2aAIIROk14NGq5ASJc+rqciZAZtXRzYEZ9Wu/b3ITzQFkIP67RrXlw572i3YVx2Sp/tbBCrHKiw2pElgoNvwtY5PxVJ0H5KQR5imBH2CybGt4F1zI61ZY8lsUHK9X2GcLa36UjscivUeKBzeqJe3ZErlwSsj6hnI9mbrdL6hBcI9d6S3OAA1uuR6TpCszaeSY0fQSHu7Lp8FXIx3IwfQZFBEaF78YEFP48qvLpGr5x72yndcgF/DHALuMt4Xi7kt42XDSTC9Suc5s3/osMNU7R9sitTtlHtVHTSnRC4nR3SJC+xYF3urJq3ViuLV3MZV8VDkEhxfo4c06pc5hc61N2v+B2QPlXJNX5jqkQ/zrsv8X/RNC3A2pX4/RXK0PE8qFtb9q/bVCcB7iys5mOpPsj629KDqYQcPVMueKl1O2sClYaQk1vIqGr5WaQIvVmsrUHUPRg1cG8jSM8LokAbNyLXiMfxMbs+cfd/n1O6ae9N6RrRLkNlBJONMx1HRNSXbRqnznb7shr5EiVmWAV3yJdHww4khkdY3H6iIS7cyfCrzeXEBGhwM4+DQfMHbdiIrNU0fcoiRaFqEGizKy0VaizATDhhOLJ1AJS2FjSb0SG42HchrKZ200pHNZp20a5TLh97EdUrNOGfJ7E1HHzPnpyMSkeq3E11dG/eeCZLPBG0GFcqwvbGplTbZ2UrKVMUbxkYid8lt77jXxneMv2+30w5NHKUhFu5N9LseFBTTxScxCGPd7sWrQDjL9Y3ngM2EjwqDukkifdy6eoc4DPm1mWLBX8TYSV7AgYRNKD0XVF/SyMxi2xWxj0/x2+smHvJO++soGF2yh5H9E8Rhweej5gW7AuckyK/kaEoqu3Sfi7unEyL1e7tcmt1YngmSug2uM4T1Dr0zyTjM3flcT01Qx5houxgO9zYjHyaopmbqDIYB1aJtDLPghRfbSKqTJvxCoeLLRFXfv94w41k63+f2ed3tYqK8m+FkEUOvxjkbvKc1dLMJWvtqjdytEBOd/uxApAZvf+7yOCCmwDpEXzKhoBSHu8YYOA==,iv:vf9rCgQ2tqidq2olNStx9AevbwqUF1ErHX9fXB/sgyY=,tag:noeKGEztiqylwirforgF1g==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQWJSQWx2TmVPK01JNWpm
            aFhDZEhwVWNpMzBIVDlZODdycloxZE10d0MwCkdpN0taTmVLVGJabi95em1pK3RY
            MCs5MldpRWgvSDJtYlAzdEFiZWkrNUUKLS0tIEl1cGE2VVZqbTlmbU1LdVlBSXBm
            dUhwaGthN3IrUUVlSmpvbmdxM2RuZ0EKmNaUOyz1zHeI8bcvu8OngWGZZ1wBX/0+
            2dtjjaEyppv/csjX+s6JPi0QapsgTS/uqU1ndvasl/gKj8ZRa/9+Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T17:12:32Z"
    mac: ENC[AES256_GCM,data:H3vgN2QnDT1lY03OoCsoKbwphc2NmtdZce2JhGKOVXtXMdbwuBPPFNhy5uXDbbQstpBYfliZJrFF9jFywVl/vVKVk4nplOJp8YIT+O1O+hASs+vSDBlTvDputij7wV8OyrGJykGkIwFTtH+w69mFK+0i5iVB9ALwu9pmnmBQN24=,iv:2WdvidYM8nC90pKnvy8t/PxD+vzWYKVh7Dr2Wadik2I=,tag:fmy8zBYnOFhERAbl68xdzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
