apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-gotify-config
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:3x+KHLD6zlfd/uZjI3J6+7TtJOBQXiB+Smsp2aNOziHWvQu4B9MisMBu9BXhSZpeWxPZ87ZODIkMS5jiG6yth/r2cUUod+gfwv5uRMTG7Mg9qkP5zFFSueDEnlo+Nosnvqtd8aJeK3j6ncGW+878w4IDF/DzYfaSjnjqxHE6rwGetZbXFiF5GCE0xm5KIGaYjTx3d4kwFtWcxHByeEZHMOUEaDngrxj3tfTXVt/xlx10eVnp2sIeigcTPJQQWoaGIVsc7HSS0Pb/UwR5E9EikIK1C//q8D4bw0dsFX51y4Ch2p5Q6qS8ap8ozjyezvze5JbK0asoSn7I+DFteJ6BReY7iiCRbLLRtt1T8jL7kCJnClYHcHC+f1y0avDEqKmTS/4jAHtN6kNFqLr5STpNP+R+Rmj7Q7UooIsGo2W5pWUuuSemViilsJGenO5aBUG7ICN1BqZSlPyeAgtxf2bNNYQvx9zSAVhaFAE1xomagnFofBNGzxkt38eRf6lGDB2UH/io7C0sdLzs3IZxPoZUu97wvlyz7JP+YtMNZRT1d6FYpfkYlaWoJt2taRtdPto03QAoSl6KFy8fK2Gpr6VwWAiVX9eWoJZ+YscwVMVIaTeCOf+WgpF+22kse2RCwfyVp012HoSneh6Sc6D6Mnvx5evPQ/QDY6zWw/s4B+WbOvBlKmVOddZvmDFoIGdDCvcyRx+2mcDtPgeAbFPYlqQYhCQ0il3NG5pqe17j8X3cjEoR0GKvR7UdN+gDeLQDmGT1nt4o3K9JdkDD0Vch9mvBCu33ynWx/W9wKCD7E4kMOyk5dK8hSFt1nAx3iJEqbbj52f+cXy0RFenUhFD3nbX3A8OpW/9ZlcilKhpkdxrHw7q7Nfc6dGGNnM5D3FujJuM=,iv:ntOgWdmauuVffySzEKh2uZLGfcFMNBiEssUG7G7vMow=,tag:8kXRSQHGEhgNfLxkjGkaMg==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNUJ3aTBFeUZSRVBscmJH
            WWJKck1hTlJmRXRkbWRxVTRBOC9OZ0pQMjNJCi85TGN0alUzQm10NS9aMnQ5UnM0
            ZHlodDBnN0Q5UFJSdTR1eW4rTUpSUDAKLS0tIE9zajBMWTZUUWgwUnBnelNiOURX
            WWIwV3AzUEV4UkFyMzBHMnZNeW8wTzQKdzJn4jx15npVrhlu5ZoL8OSaea/VNiiW
            ROmeMOhN0XHMhpEKL+nTjJRO0bjRhh+jxVIHOTlZhfuqQG+hFTYECg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T19:29:45Z"
    mac: ENC[AES256_GCM,data:8SWjE7pKBiBPzyxjVKGSVnHZywinAp9i2c0IGIZOwuBa8eERJl46IZtjkzoxn/IMFqXadZ7GdpJ5w1zwDyUJ20Fk72KnVgXaQaA0b8JANLeAvBEVnjYyMU1HYygVjcBTyv5NnUcqrto+DQVMbZ6RYt3i0YAkxwfcMbb6asDNM4Q=,iv:6YvtuwFadYJGtqCoePYq97lhTmws9BFIoXrDIpyKIHg=,tag:ZaAYXTvkIpfW+6zj1n9uRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
