apiVersion: v1
kind: Secret
metadata:
    name: vmalertmanager-vm-stack
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:VI2baJNk7Tj5iM8cXBM+viBfIQ8JEb1jqXzgHpHjm4yxwZ4OW9l83HhTjEdUSWipwAHsUzNzp1JwGUjJtYL6Uyz6PGzOXVsXeD5bNUYiXAy6CHltMlcMtY3QGg0plWQoux+xwK/4Lb9VMjG2tGMsH6VWuxgTXDZvWFecUJcp/9lSSPOdUnNIDHbkdiBZjHg6w/UYp5LT9SRtIf39Vyco3mnFFQafNRUEyq7loAi4ShhhAVN2E0dK2s1Gb45azGlznG6jmXdQdoSS9JA5eK+IxfA58yW6xkx0Hjef7UYQUyJkZvjtFnL4nRTrKM/mrjsyo8hauaMmo80D4VRqRzG9bkI2Je8AIgrYAm3XetUhCW9C4Ll7SYu5woQy2wWSxsqu5hoD0C2KbH3hmTgMJsdvTK5EIVug6lq7ZEPl6cPjRoNKNcW+OcqFUFt/PwuM4zQUiiE6iRFfppTl7bqsJfbWqwyw7Rr30Jql6VBxRVPkxiwmUBOKRQd9zyDxiIlwj8rg7kVDf434zf4mDKmTnSCwT2KjxSO+NrE3psgYBAqVkOgKIJArUjeL0n7+JvrMpudiYWUHx6S9N8Mfc7r3qYBgE11NXRTw0Z80/GXUkCgiVnmdxdC3WEKKwBEHG7wiNeXNlLXMTLVo1hTylBwRCLdXLS2mKmVir4eaeJZbffX+s8ak7gLYgqopeF/zlRJYyxAyuU2KVqAIkmA6x118i2gMZFo//N8R0zdbYJhpS42IFpfVQ3vlkDjROX6ZY+GkKOL+OZCt5wmL2zFk5c/luyNYWdxrbRV62THG2XmsIySXoP1tf+Y8MhKfLy9UBtigWyv2y17Np53u0QHGbl4nKDQmO021rzUbeXJPUKIs2tiancksY4F78grtyICU2dBELhovqC74L8zI5NXJzCCIVKgXpo9q3MrDJ5giRwVG5DPjEAxFvN0XI4aKvcWFPZMt8zgRtVY/hFTaend7F6Ukq175IDmjeVruhqV91jZrN6eCDHMl7vkXy8PKVobMNaXNEssUPX31BFlPyAdYeT9rctW1lxJma2todpSTNsnS1MWi6s0gN8ypJw/3OZW6L5dQi8Llu1aCw/b+C64nOWL4ziROPZHIFED2O4zYqnOqEigB8RBwrRgZwFjj95RnHVIEoklR2nBr2gKmGTG+dO0Rys2E4RYpL2tH+SeXgny+UYcataeNXk1hWztP1RMmZ/WC3JDR91P8w/RUuY5iiNT5FJSMgcZoW6QJYM/+Ew5n7ggN+x0c3RtPFdQGw72T3UwochkCw/Bmy/heyNfbE38MWxe/GhdSEghUn2iFs5HKfBDrI35hv6yYpVNsSJwqBFtjp4eSd27HL+y3DT/U,iv:9oooCEPciKrBSNd8d+KAHEvMnSB/73A9BMfLKcF9MXk=,tag:L5zpQpiSFocj80apJO8G/w==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZTVyU2Y0aDVsZjBXYjFD
            anVFbkN2L1JwQTFtbys4Ymg1bWFZZnk0dlUwCndkT3A3QTZRTkVsZ0QzNDE5c1Bx
            djRramVvUzgwcHEyWGFDVVZQcUo5emsKLS0tIGM3VVdjSWUva3l0ZlJ5aGpCWEY3
            N0s1ekR5U1Q3UUE0RTgwdzBndGtza1UKvJvhaeHviRD+jTIvRBwRGi9TxUenv2gf
            JZobKkh3ReZ5sYcLrPyuOaO2ynhM/mu3gWKIn1EGYTFXgLjgV0wQhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T16:42:42Z"
    mac: ENC[AES256_GCM,data:yk+dbWxg3VN8AhvYRD22iKj0zbCyU22HWrouo5dZvAf6Rq4mLM7Gu2jsAFYtlCNtPrxarS9+DXd+7SLmEW7nxOET8BOQk4BuQWzGtYM2w897gX/Iq215BWH9UptX4agKGlVsy1NdhprFNrRHgB6AgtrdML2v1FAWKr3anQ3Ie4Y=,iv:bg42HczZQAEJesIWLz5M2CYozknP/4OLE4QFiUvWwuQ=,tag:R862Uzi9E63Kxf5agZREfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
