apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  timeout: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: authentik
      version: 2026.2.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    blueprints:
      enabled: true
      secrets:
      - authentik-blueprints
    prometheus:
      rules:
        create: false
    authentik:
      existingSecret:
        secretName: authentik-secret
      error_reporting:
        enabled: false
      web:
        path: /
    server:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          interval: 120s
          scrapeTimeout: 10s
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          cpu: 750m
          memory: 1Gi
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: authentik
                  app.kubernetes.io/component: server
              topologyKey: kubernetes.io/hostname
      startupProbe:
        failureThreshold: 120
        periodSeconds: 10
        timeoutSeconds: 3
      readinessProbe: {}
      livenessProbe: {}
    worker:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 300m
          memory: 768Mi
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: authentik
                  app.kubernetes.io/component: worker
              topologyKey: kubernetes.io/hostname
      startupProbe:
        failureThreshold: 120
        periodSeconds: 10
        timeoutSeconds: 3
      readinessProbe: {}
      livenessProbe: {}
    postgresql:
      enabled: true
      auth:
        username: authentik
        database: authentik
        existingSecret: authentik-postgresql-secret
      primary:
        persistence:
          enabled: true
          storageClass: local-path
          size: 10Gi
        extendedConfiguration: 'autovacuum_vacuum_scale_factor = 0.05

          autovacuum_analyze_scale_factor = 0.02

          autovacuum_vacuum_cost_delay = 20ms

          autovacuum_max_workers = 2

          shared_buffers = 128MB

          effective_cache_size = 256MB

          work_mem = 8MB

          '
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
    redis:
      enabled: true
      auth:
        enabled: false
      master:
        persistence:
          enabled: true
          storageClass: local-path
          size: 1Gi
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 256Mi
        args:
        - --appendonly yes
        - --appendfsync everysec
