apiVersion: v1
kind: Secret
metadata:
    name: authentik-oidc-clients
    namespace: authentik
type: Opaque
stringData:
    headlamp-client-id: ENC[AES256_GCM,data:20Eo1HgBtLlbDo1/94QouxDaxS6ROsxT5kgMK9Y3SNLazNqPGULOcQ==,iv:FgECEfxE1h8mjE0fz6x6JrzgvodLG/cX2QyKu5IpmHM=,tag:6nAkNsalOjjs3zvWDs5HJw==,type:str]
    headlamp-client-secret: ENC[AES256_GCM,data:njllYOA/YW3G8qVM0ClFm2ExRz8CRg72/4aHxQB/b1WB42yb7g78xiNB4pAJujiN0fKvEDKmEuNYsvAkJxogCwUJLIjtAamruxvwXOE9GWt4V0hpMVwLr+c6gUSf/t8fuNf07Xf8MrlapQtUmTgpZ3yY8jCdNI9f0ZiG87lKvOQ=,iv:2Eyb9ykIMbkeLOfsw9h6ms+EUEj8Mju9xlIURB4bYZ4=,tag:vXPQBfAH/RNPUHutLgl6LQ==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUEIyRDNCWFN0S3c0SVFq
            aDBleTc5NGkzV3gyUURDdFc3SHYwTVBmTkNrCklwS2lVM0IvUHJyV21VYzBCNU01
            Z3hjZjgxZnQwcFFEeHZhTHhYNDVtSnMKLS0tIDFyQTJoZkFUZzN0WlhnK3gwaXNl
            Z2Y3Vis2M2VGakJKR1pydVZjM2hxSkUKI05xguEZFLZi35HTjkDNL7mIvbva6thz
            4TfGEkR+oAsgIc6HU6Vpek2whDMasKA3dq9ZtCtC2qghAy5gY+fCzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T14:08:03Z"
    mac: ENC[AES256_GCM,data:LKwTFtsVsFOy6lcNNSu8Tg3EegPS2cVRjoewTowXlTOFIHmXKr/n8jAaMCYt/seQ3TOciHwbUVqiY62dkiSirNZ/CQfETo77CUJA+sSww0QbFDst4xI27ZIA+irN8DwtlrZ1xy4SdXG+BMXO+jUfI/CNM1qLtTJ3KGRg+fJU8oQ=,iv:QezIDMCe8PVVeDqKITtcctTKogtZ06l2WiAAbYNEkUQ=,tag:kV7k+su5gzzax4aGj5KJ4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
