# ============================================
# authentik/postgresql-secret.yaml
# (Bitnami-style keys so the embedded Postgres uses YOUR known password)
# Fill value, then encrypt with sops like your other secret.
# ============================================
apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql-secret
    namespace: authentik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:vmF52lTSPi7yHOPKN7kHNCbdGDmTBJdmduTaG9NnCSZN0DsXJwafWZoZZBxWwCM=,iv:oNSIgntRZXDg2E0Y6w3vIEYJpE5cvaopTWjFchie2zY=,tag:lye8yEvni+7OJrvrkzageA==,type:comment]
    postgres-password: ENC[AES256_GCM,data:+KlkJqZ2Nr27zy5vFS3q8Mja/PiGQL0=,iv:A/7jQnHg7D/vWzLXYImnrBlO93jKIZAYCbc7yI/YYfQ=,tag:dDYYfyMkmXY1nu5PM1265A==,type:str]
    password: ENC[AES256_GCM,data:eNeDDuFQ7juEjEMVNzo1hbBSPgMvF4w=,iv:B3rLtQoKGXguo4JPyhrFwGczy8Rbnv9lYcCEIAToqMg=,tag:de72qZHDyjHZu8t/BbHhXg==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YVhaeHp1VG9KVmQ3d25N
            UEhRcXVYakt0T285MTJJL2E5M0xxaFZOdldnCjBXcFBHRElyRmJWNUU2c1FvTGwz
            WXdqWmU3aUgrdmdsdnBiSXR3cmxJY1EKLS0tIER4ODNKSytybnM0OUNkNVdPUDQ5
            WHpCNDErTmZOcG5wajJLRnIzOWtUUncKpxSLAR3wS+L11pw1gHYBJay2QuYP+OmB
            snSE7jhNgymL7xA+fH5UrEjZGCgbMxinWUcsxXl3/K4Vn35cXgk1+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T19:20:22Z"
    mac: ENC[AES256_GCM,data:BrX9YRJJd3T+8HHP+jH5cP0PTpVTLeca0TzCSnhfWEVhF9AsgxihLsyIiqALHTYTdXEDZVqBJv7RFIl6xAEJlp5PmezflKp9ENWwbe9MmWGy/+5+kLNG+C2i/Sl5jGqz+Z5o+5GPwzoQB+Xg28nKwbU0OFnVtX+1z9N71Qc+SyU=,iv:fonDC/3c2esWF0UtWJ1+sItVbT316SrYUbYqFox8GfY=,tag:h6DXo6uJGvy7v5mUajYeSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
