# ============================================
# authentik/postgresql-secret.yaml
# (Bitnami-style keys so the embedded Postgres uses YOUR known password)
# Fill value, then encrypt with sops like your other secret.
# ============================================
apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql-secret
    namespace: authentik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:hfEIftVmpKv5HLo3J1LoxCl0/YCovv3K97Lv+FNLYseAOyEK+JaAQBxCELKtShs=,iv:tc/8qBZbELoAsRY/dPXu9i7bA6u0pJkUxefvJ2HyIM0=,tag:ijE6t14YR3YFblX5wppipg==,type:comment]
    postgres-password: ENC[AES256_GCM,data:yBvTw2XYcnGd/+DyGwlc73awrVPT09o=,iv:m8/sQpyFqQD0xZ7yh1Ii12nSEELbDXFTdUX6kCMvVWo=,tag:UUGSVpPggSaD647LAYWI/w==,type:str]
    password: ENC[AES256_GCM,data:lPPVTAvS2SZUK+KC8UZxiS0Ekc4Q80A=,iv:8IxPXXufELY31x/BMFW3GswpzE5+yUxlFaz4Lv4GQ24=,tag:LOCsmzAdqCZGt1SliED+1g==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSDRySVBoVWFDOFRueklt
            WTY2SzJoeE1VMFBQOHpLMjBnQU9VZlV0U1hjCitmSWdMSExxTTVSYSs3OWpJcHE2
            Z0Y1RUZTRXp3MHRiWlRINFhWZG1EQm8KLS0tIFdvSG9aVCtod2E0aU01OFZnNk9S
            ejNTTkpONkZkSU9tdkZCYUFNNW1EZ0UKghA/kHw7CAXmsdx9LYOw0McG6rknp/1c
            PtRAg4307FAP9D8V7lnXDf0uN42VdGeIFuEbCl/5I/M3HYtypS2eXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T22:00:14Z"
    mac: ENC[AES256_GCM,data:45uzb0F2C6YvoyWLhUWIuECvr9AJ825ykj9P7uCn18ZaJdeeAClvtKHoAFAKns4Xdce+H1JQBaRjw1jyhHnrLNTfDTjD62i6VfhAxUBSPg/Mq6Cgj1xZsGduHSNet4dKKFs2E3Yq+8pzQuB2Gn8pyN9lUIVwCPjffeTY4pa2VFk=,iv:O18zPPYzVBGdAqzwSiq7yo0vFaGs04fLGQUXpFA/t3s=,tag:QtzFDtsZ4/19h6CDFwqy5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
