apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:PITRe3O4heDbWnBRIAoTy4c8A8UpYpH7eCUKLcNpM/ALwk7yyOi0Dfu7pwotDNSegZj/A8nclMiAtEXhUBNTQApeVvAfRDJCRdlNOMkcAQkjcotfXDwxnQ==,iv:jDDjXEUBOxqtxgpNneFqzibE7PmHDOa9AX7aHy/kpS4=,tag:HTW7+csBwnGSqA4UCEnB/g==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:RyW0hKa0R+rCfpALrpluVGV5Y8g/5ldcKcmtOr6BhPQ1xr27m5OH2vkzJx6EtYnLe/3e3SmeIoQanJBBfHKB3g==,iv:qPNh4tIAH5BkOBXlEYi/qBJwKJhgyNqHexdOizWLvTE=,tag:E6By8DMsICBuJikDrXH0WA==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MFFBSG9weUdrMlI5M2RB
            aUtWdEtqcFhIcWNpODlnZlNNSGtmSTlxeVJ3CkNqcDNKVVk2dmY0ZE5wWEhyelB0
            TWtWVXFoWFpRTW9zRHVMR0dZU0h1Q0UKLS0tICtGVkhSc0ljbkk0TVVDS3ZpUStS
            RS9xTFFTSHJxL3BXS3A5WVNSNUp6Y0kKsIgJ3OCKFgYTJc14BArhJzGUhZ9c34XJ
            As6aEmMesg3N8SYXi590qERW41LXhXDz0Qvf1yJHUonYs1PFKGrk/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T22:08:10Z"
    mac: ENC[AES256_GCM,data:lI58yBJio1pleiMHBltQMLQxi+cD+9dzfBIUfyEeNXaUKp4c65psW883qxuUBfwXL4ZvnD1uwCAMclK2IgmsFwbU3Mxv7/x2GEWkWjSq6k5UPJrnx0MQVlnSUpKMFPOmworsyGw+I1XgekU/Q4rrrQp8tDxY9KFD6AY4xaInG9Y=,iv:0WNW1qnCtlzwpTjIaA99ousiiyHj+CVV9KQ8ad5uo+g=,tag:DmUiTSrzHn/G4bIfEJ7JQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
