apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:G07c+F/Iqy0VYXuh9GlIXzv/jUBQ2IYfV2peGtRwCDU9B5FJE8GpbLHMi+xJO6GhK45qAIMbpPwGSZ09QSS7P43B8EgRm+0HwqvGVGSD/bop340E3XSDIw==,iv:70kEHlS1GpIVEvMwLJl8sQNz6ONlRt1Uen2lL/7tZMw=,tag:gD/blg85Fc+p9F8QoLXuNg==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:Z83xuyov8HIeurAkgM5CtcH8EJi6PyMcfsN3MK4lUwTiWAPJ8IokBoISiS5Xut/m,iv:DweC2tqsOBAvoPscywGvRo8gMy4iKiv9BT7Pb1oOinY=,tag:CiDDUdsOjowHaESOTFZBFg==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:a4LeeQ==,iv:44SpuzSVt9/2wVJpvClrn+7LgYs33woC9OL0Fgi0kTw=,tag:Tszo9g8lPubojcv24A8Djg==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:3qYQ/IC0wnMJ,iv:AKge9zE+p03olAs/kWBX4zdHsweaXJgc66KRI9KeTx8=,tag:b27GSGIZN9Gx50s15oiMiA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:ROSWCllnNz+x,iv:v3N+cvxxT0nvss91yk0+fCGHlGfrlifNXzfiKNdNlxs=,tag:7S9VJg6Pjt8VQyRA738/2w==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:wxMd4TdgC3RcGmfX20mHat13mXNErCs=,iv:Ba8SMtBY7FiPL71mT9PGbhlcHBYb1RL+wrsR7uyomTg=,tag:Vzj+JusPd5Oug3EcgaIOMw==,type:str]
    AUTHENTIK_HOST: ENC[AES256_GCM,data:riSg/MKRE04=,iv:fRTgGWbLYZFXguCJm8liD5Ee2xN5N5lRuSZGwmEa6DU=,tag:i7hho1/atCo9bxRgLkn76g==,type:str]
    AUTHENTIK_EXTERNAL_URL: ENC[AES256_GCM,data:a1CEiYx/7nh4+mDwhgGR2A==,iv:8RsMFwdxYmLb5JPhCWFvUcg7zWCkz+Be/8YN2XL+4jw=,tag:3FJ3Pq3N36si4cXtk/9+2w==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc3YxcC8ra0x1c2cyTDZX
            YnlxdURaeDVaMnJ2bW8zRXJrdUlIWTZaOUFFCmJ5dWpuSHhlY1FobTByamtsUU1L
            MkpmSFcrTUx4MEJBZnp2aWxUQTR2eDgKLS0tIHhYQ3pHUXJJWnAxcXMrb2ZWWmU0
            MWtpaElORlZuMDBtelZhUEo3T01IVncKgxb3l3FzQD5BeqGy0bTSNIZSY2dnC4dn
            WXcm61ZFOpsTOSH75YBOhDYjgUfhASLTeTRPg9KnjahFpK62mQmBpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T11:28:17Z"
    mac: ENC[AES256_GCM,data:chQfNeezBDElnZdb7uMmRXCrXT0KE7sGiDK2YwQmIkVEojynzLT4JqBk8gj5E0VtWSyYkAocTZux5qhUq0Gx5lmZyG+DcwNyjZuEP7guxmRtCNbAfjvVT9dudWC6LSBaUvBdkSdt9mmETtmdrQx8AjHKl6sjMKp/Wbca9KtuAr8=,iv:nSKGvIYRSgv6SeimYtIUHcKIR0PSL6/3xDBmGLlKF4c=,tag:GVOXNlnG+iY8+ddLdKKWsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
