apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:AvYw+K1mZSLwM1pjT0gLKPWjRAfSRww0MdoxSwPkEw98VKI5Hz+0nlPCHt78niVXO+JkqI+BHg0iXqr9s0czm5GH+Mcf5pEmS5gX9tU0zlSnMj/LLHBDog==,iv:eQHogO1aMSF4JVzqZDL1oU9/vxLc1v4yF48Weft2xRY=,tag:mCZ5s2AU00bkcpdN1XVdsg==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:ZzY6MTgnnZqkkROS1URMvI3QlUW25uNLBif6m7UnOugnF15F4EFewWv0gXF6lg73,iv:Nhj1VTMwIC8gSmgYR6VtOGeDpvrfKSCnnbDOCKRGptE=,tag:7ywX1LrxNBxieAwDAihwwA==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:c1CarQ==,iv:kNANnz+aZQyOrBOBuJZP82Q6EjcU2nYIyD+hzqmJKO4=,tag:QBwca8EOJ6PEc9ExAirPQQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:aY+1AZluX6p4,iv:LUHApx9ridkskFJcIhnLgVPEzKkduMB8hNJrojreOww=,tag:kOSH+WVX3BVoPLzdmrlBxg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:K7zd7xq0dN/j,iv:cf10PDl7DQmsLjldMyRsZROVcZCuFErKK2i3vQxB4Vk=,tag:LBh7DHki9aziRUmH11HMmQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:DLDmd+qDEBKZHwPPc8+97NhNK4Oi49k=,iv:W7SsqI/hsXhEjIKCv1dSIJdbNhwIrLklqUNOIsqtF24=,tag:QL/4T9x7zugNYmCmoS/eGQ==,type:str]
    AUTHENTIK_HOST: ENC[AES256_GCM,data:73gokFjVVZo=,iv:5iAZFwIAcKcO2RSyJ7ln/t6Y+MMeFMqSqJsVhia2ZuI=,tag:0Lz0JF7zw8J2gDN7MpiNIQ==,type:str]
    AUTHENTIK_EXTERNAL_URL: ENC[AES256_GCM,data:ZzLAymmTnl8KUpaAJAI1ug==,iv:rQkVWdjXsKT4SQKJko7ZVFClLxy9FlEtSP4NtK/BRCc=,tag:V0i/ekA/5xqqOHWapFKA3A==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRWNwakc5dEE4VmF3OUsr
            Yno2OVVkMHk5TFRUczhLYUVUTFBaK0xQb0RzCndCRmQxQlVLaFU1ZDY4RGNDZERX
            MzI2ZXZpUjlYV0FXdFlieVdMU1Y3NjQKLS0tIEllTHdpVFdPZ1dxOGdUL04zSk5I
            SzI0TGxvb0hoTDh4SVZZR296MFQ4dE0KWFxrMQY/ugr5EPLmgTYV4yA86JY4s9Yy
            JGI3ffWSaR3WKacvI1EKxnpeTTaFx3ePpiSey0rXrJ+ic3fyVuE9FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T13:24:28Z"
    mac: ENC[AES256_GCM,data:qy2RwsGgcqG/Z4zFbEjq6Bzp0lIYu0MycCgAQ+D2Fude3qtX/Fwdq8YE2mBWRD/Peh3bGJfXXdKcTmPfVmggs8aI6XG2oRI8hM+G+aFRndYXdfxLH3sRuoCPGEXKwe/x1xB1NLdcMzuFPXZy9yVEqaVNb4dI2Yk3Z8EzuzJ490o=,iv:PqNj/5uEmuDQfonECgedCOyhr9IyC09v90jCdi3XeBM=,tag:QjKP62jqeVV0JbVk/iZgpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
