apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authentik
  namespace: authentik
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - authentik
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik
  endpoints:
    - port: http
      path: /application/metrics/
      interval: 30s