apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:mTwRIDWcQL4VACaRJDk=,iv:7JDx56j7gbJndFfDbDacjd7sY2McE/jvRZcLrvIqpAo=,tag:WmrSNO3O1/hcrLohWR94RA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:3hiFi2jC,iv:JoxgvendEo726tH9a36Wj4dNyxr1wNbM/HLMXnPFcvE=,tag:HwgA9gAB8gzumeL6OGuAaw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:kIsOc+Ak,iv:bcbqqoGncF8nHz2amVVRYJO/SnKZIzonpk71/39Otdc=,tag:3kdkbUPNHgYU7dX1caE3iA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:RBfZlHtkhHwb99OIoiw=,iv:dSDKSp17L9co2YRvODrQUsApTRvgYTG48lISBZpFOPs=,tag:RwIxvinFb+PwV378N0WxQQ==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2V3I2YXB1bXpmMW9wQ3k1
            WHV5ZmxEQ2dOQ2VZaXVFVFBXU1BJRXlDSVZnCkhSVDFWK1lqTUhWaS9nYjMyV3hT
            Q3FIdE1FUlhQMjFLOHNXRTZBZ1drcGMKLS0tIE1YbE1TSENmN3pSdnRaNEtrdUtN
            REtwRTgrUHVIbXo5ZEtPM2tyTmY4NXMKV7Px28jZ7C3Frbdr0t3Xf4F9Cczl4f61
            tZkKbienSMdBJHSksQDATytPfM7iwMElg2LrIlswL5fprLNmYzH/CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T21:24:32Z"
    mac: ENC[AES256_GCM,data:9p/9bAMtPMwyuTtphaB90UPeP0oJoikqUNr0/cxiu7nlO6vXvLdldF2QAB6OqCgl879izGZZVt8kL8S9UDZw6NEKMCacZ8GTOP4sj7Vcu325EsI95Kl0qFOaOrKnjnABJrhC5x4ixTWPZisPyH4BCqJI0frn3VQbXwj2bwX4Bxs=,iv:blZ3Fxw/RMxtAGMt3ftpcRi1NCb1wVgDjq1b+9qRJYs=,tag:+Z3wYYPgIEupVmIxmILJjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
