apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:6dIq1+LWT7xzBTRTP8E=,iv:IWA/g+C+v73BbrMknk/rLsvVFrUJwgtiRY2HBH8OWy8=,tag:wvKmlk6enJrwKLE+/iUs6A==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:L4c2LQBH,iv:ggEzyWdsWNtWUcFxrc4RR9TaD4f/H3vCKS1kKfmPS7I=,tag:8ZBuwf+i35Nn9/hxxW6URg==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:7XSPJU6+,iv:ZvRUTpsuY2vEZhPdJrRcGcal9RR7WIkGG6sxlDVmkGI=,tag:ysGzPZkrdDeKisJV4xrDdQ==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYN0gxa0xzNDcyZ1hwN0pV
            NFNtTG9UVHZMUkpTKzVId3djdFVWeGpJN0RJCmNpZHQ0SUQ4cU1kMDRUdnlvZXlD
            M3dzUE1FUUlNLzVkamFBL0ZwWjR2N28KLS0tIGJJbkZLZS9nUkRmUzluUFNEK2FE
            MW0yUS9pMnFnenZRV1EvU0hma1k3N2cKCXAdBfCJPMVTsDr9PNRHAJ4pf/s6PbiX
            flSnmBSMwHaecnvDUHaeU9aox+DPiHkZGmZg3Ms9kdwT9hroAwoqAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T22:46:12Z"
    mac: ENC[AES256_GCM,data:nhcdYJHIZaLn1cwPl82C5P3ZofJz2eJnz7L5WGSvomzltYuDE6PZKMf/XiUAyxdrCksVuhzMXEVixDLtKext1CHnE3UjtZflXkj0Ceoqqt+rLnOXVRY6KC7l/t2y7KoMTvFATGStNZ/NA3AcfOEZVkMEFNZT5T6U+CFmvf8LXhE=,iv:HejTfPfYSRX+wnmIRb+Fol7qnA5E65ttJhgnlZ9ZoEQ=,tag:5ARtNIb64RwbQqrm/+kUGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
