apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:LL3f6n4HCpM8MgCqizo=,iv:NXNYez23qSwDvUy4f9kFOtjNE5eG6WQ0SWcxM43rfzs=,tag:pcNwYzY7ioXD4YXo08ZPOw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:Es48lYR1,iv:r5jin8cFXVHT73s8x+M3Uxj+LpoFtwexpRhLLPnY4l4=,tag:3W3oLa/USXhY7QhcDBcIww==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:YTJ1Uy5I,iv:j0iEb+eEAEFZEaxBYm2YuesJhGyG2jlvMG+lLUbni08=,tag:9q74MvOT25tJFAGd+Lg9yg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:l0oyxBG4boniDGUiTCY=,iv:bomoubZXtLH11T4fdagUO0E5lpso4qbBQjP7I5zcvTE=,tag:d9dT28lKQEnIYDQiTSn6Ig==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVXNuWkszWW92RCtLRmNn
            L2ZtRjBXZE5QSnNqZmE3WUlYbElqdVV4andnCjUvejc0ZWdWUVQxZmJidTYrajRm
            dzRkM1E0ZTNYTloyNGJIZEFjL29aem8KLS0tIDB5UkNoK29Bc2N0ZXJwSGxWOGVx
            M1F0c0tCRy9aM2FUZHpYWnlkKzBWNWsKxKTM4v1Nad2HYUQCpPbgBQXJ/oIC+XUL
            hSb9RIrDsv4MWXXZG4/2iM9UbLPpgXT92cnKgrcia2F9qPYA/0S+Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T21:12:58Z"
    mac: ENC[AES256_GCM,data:lqh8ic2Bd3FRAkpvc/Pvn5/H9WvhnfWJkpJD1wezmmFvmNwn7bqvHjP6M6ZXkNfVHxcIAX1HdX1nPEhpCqgmBnUW/N8rXomZlB2zyhC2cUsKCWJaopfvg4UpD5AX23D5SmP174roaIgp81ItEz5Mnq8gY47LSSY39KiVk5a5bi8=,iv:8OiSg1Ja8yap58YEmxxhaZ32bJ0HXdeU7ljPGv+goW8=,tag:V5e/VK//cPLbQ65NQnqSyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
