apiVersion: v1
kind: Secret
metadata:
    name: gotify-flux-token
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:2RFUZHG17eaZTp8zv7qFKWUw4PMC1QlIhB5fB1MTTqeleHRemIx5LiFl0BZ0QEHOwrwN+9WDOs0j5LmxVSIvgJPpeSA=,iv:A6QL5fItuqjCs4XYygktkFXF9WLcpYumU0Oouu4t6Pc=,tag:ArIZWCLpcG8gy81RAxjkdg==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbWloMms1cXhzck1IaUVq
            RVFrczJqU2FvSlRrU1lnTTNMOXpMTGloemc4CjZjQ2tyUjAyMDFkeURvQ0FPNXRQ
            OUpGVWF3Si85UVlhay93QzBtWGt2YjgKLS0tIG5Od0Y3dVdYMld5TG1SM29LK3du
            MitPME1jUmlIYzFpY04zOXIxVUJtMW8KlxCq2yHOigzihAhXWLI/I8aRKHcva+ot
            NXgDN7+ESenlIrv0YT3CDWD07ivYiftqFlHku8M/K6AmdhiA7er+Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T22:13:11Z"
    mac: ENC[AES256_GCM,data:POXKOO/x4x5ibINtQzpvMNx9psL4K/v6trjI4o27CplcT09Afv3BUcbSH9pGZ4tNSC8n8VlyvtqNN8El+jxNZkTahUOJUW9fCrA66Zv0o24+9F/fI4IG3rbP1ervSPYhKdhJM6RGEpipwMGdn2tT0crG8u5nHf0gjUKwGzEsrOA=,iv:Ef5RYgvO5Wr3ziBbpAx0YwmV3RrcZNZlreFHkbcNfCg=,tag:PpGqE5O4BAXZ/sEco3PAxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
