apiVersion: v1
kind: Secret
metadata:
    name: gotify-flux-token
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:P+ZWNHtTVjMTBYb4nFMERYyp4DUrUlS79Ql/G5ihb2j7niQkKBb52lKILgaZ6usm95LjEdGHHpmViDOY0RTB2mPGCaU=,iv:k2m1ws/Qx93+4iyk7ezncchlM6UfZOOc8sc7yIUDX98=,tag:wAqDDqlDnmCKJ/ITk8Q+FQ==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScEd3ODJBNnZ3VHh2UVIy
            OFpwZmZnZDNJa0lZMndRZmUvTUhnWWV1clFBCmM5L3N4MWJTYkFFRVZMazg5bE56
            SkxQU1BKOERiUDZkSWlXMXc1a3pHVTQKLS0tIHdma3JBV29CN2lsQnR5NHVMa0RD
            TUgwSU9SL2xyY293N205c3E0R1J5UFEK9OQ/3Dw1spQclrTC6TY/nOtHr8F/yOHC
            nH/eECmQB+sNqjHoTIqylFw1GWoxSrrYJIMFh4plGerzvZWryS8+Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T22:24:00Z"
    mac: ENC[AES256_GCM,data:jE4v9EnEdJPZnkLOL0jDFQZkKFXQXrPBPBUaTrpEXniwQ0Kc+UAcMih4h6nZ9vl5vdXcy74MWhr120RbVR8bGDyj0wFYBz977XbglCNNPVdZ1/QD4spgkvhD7Mpdf5ko0YGfub9BSzwRfldkDBGZWPsisjn38nm3qkvQEYWkdLs=,iv:9/IaDyANNxMsZqs8W8qy3JLqeEm6AcTzR4eNDOpuu1E=,tag:KUuCbjo5+wJpn73IZ4/eog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
