apiVersion: v1
kind: Secret
metadata:
    name: gotify-flux-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:qjphGtcV9B0TZ79V3m3o,iv:XfDM9dq0rmCLIbsu/XSKvGrIijJIpqSS5pEL4HIphgs=,tag:EQ0E4msT7Qh+xRPH+9edKg==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNHdOZ2RmMyszdTUwbzZX
            ZlZOcnFsNU85cnpLNnV6VnhaaW8rRHd1a25RCmFhd2RIbnoyVnFTS0NuZTgzZ1Zj
            TUhoNUJSSi9Renp0MTR5Y3FRK1BpMVkKLS0tIG9FTWc4dk5LZDRVMy90RitkTUJV
            d2NPZTVYZEZtK0tCNW0yTGo4MVVTSWsKePi+8KS9Sgh4tE7EWiNHijAMUnfCGF6I
            nfqp0c/A84Ihug4dxJKtnEjioFot5g8BphbNCQbNtO6JM+iwERIKFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T22:08:31Z"
    mac: ENC[AES256_GCM,data:/eYnpk4V51wqA1mTHYW2lt5G/mV1uLh3q80KmFU9U2cSeIv6Ra9Zm8cEx1uoj6LdV8NpFin6v1lW0gB94zyN4+v9EZKcM29g3xUDHOmNcQBur1tqBDE6hB//54fTPpH7PH/B4r9K+QhbQ4ri4bmup1Tlt1ug58z05QnULDNg2nQ=,iv:vTAThwziQSSqFay8mr4mgYequMitk30VWNFg54WMsOg=,tag:GIsc4kILP5OdCiSLj/LmLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
