apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gotify
  namespace: gotify
spec:
  interval: 15m
  timeout: 10m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: app-template
      version: "5.0.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      gotify:
        containers:
          app:
            image:
              repository: gotify/server
              tag: "2.9.1@sha256:a3af47067ce6aad76aadf5ba32d6ddfecd1ae576a961359f039fd1831e8b7652"
            env:
              TZ: Europe/Amsterdam
              GOTIFY_DEFAULTUSER_NAME:
                valueFrom:
                  secretKeyRef:
                    name: gotify-secret
                    key: admin-user
              GOTIFY_DEFAULTUSER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: gotify-secret
                    key: admin-password
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  failureThreshold: 6
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  failureThreshold: 3
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi

    service:
      app:
        controller: gotify
        type: ClusterIP
        ports:
          http:
            port: 80
            targetPort: 80

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /app/data