apiVersion: v1
kind: Secret
metadata:
    name: gotify-secret
    namespace: gotify
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:/rdo77s=,iv:GBRL4WEu9D9vbpFSSRmMAcwg88+gOZ8QEqCenrOgQII=,tag:sbW8S8N9YLGC1lLlUzWmfg==,type:str]
    admin-password: ENC[AES256_GCM,data:3P9l+iz1oJ0/lLlM5fE=,iv:bYubqr2whnddo/V+zyxDZdXA9awiDtk92zqxcef6uOk=,tag:kfcYztBLT1t0ggqbz5WkMg==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL1lXWWgrMzU3U1FBNW9o
            MGtKb2F3R0VMOTJjSHZIbWpmNGN0WU9CQTFnCnNrM25DVlVrb1RuSWE3dm9NTXdM
            TjZvZWwwZHBURDB3T0NlaXIva0QyN2MKLS0tIEFma0t5cGM2K21wNGtpVGgwRGJt
            SGZPTHVhUisvK0pnYkM1eG5LTEo4VjAKi6dz2yZnczQVjmH1jc9o0loKMMY7EkmT
            RTaJriTDna5ZU7aBte2M4Uv//N3WSZycJgf/bQzuNgZ1p4NrxGi8zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T21:23:39Z"
    mac: ENC[AES256_GCM,data:W6X0KABQhFF7eoaF6N1weQ+lgGbk9CqL+bjrTZAA03chPdvnRjSMDbmw8KEjnRw9y6vWvCFXBKWIZzmC0lKfDY4XJMVGdLRFwueRNwAsDRbIgpjdqb40oPTvD7ASn3g/YofqSm6zo2T6InXe9yY4I2DKG3264g/S7XHuz/TV/mY=,iv:syFOYmlV4mQQOEtlvAK3Y46iLDmq4O35L+49o8MdGRc=,tag:duSfp4bD0hYWGSmxBCsbHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
