apiVersion: v1
kind: Secret
metadata:
    name: gotify-secret
    namespace: gotify
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:7YfFcDo=,iv:8nBzA0orJ7bPr+pIuBD8z4UTdpslpv0SGlZNMAHIIjA=,tag:KDLk+Lq1rtZ2SrYf/KeShw==,type:str]
    admin-password: ENC[AES256_GCM,data:C2VPHqfERwiQE/IsbJA=,iv:pN0k9cAAYCzaDRLeZm7hXN7pdJlHPUWYhTlMPQgyk5Q=,tag:oFoXsP6OyLggaqT5A0k5Jg==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTG1Td3grMmdzMzB2Yjk1
            cEROL0txZFVyZVI0Z0szWVBLUGxWMVZzd1RzCkFZTEMrQlY0QTN5c2N6RDlJVVcx
            MFNObS8zd0R5MWhqdXVYbDI1SzFhRkEKLS0tIGY2WGJNVTllVUYrellNS2ZxTmIr
            Mnh1bFpzTzlGd1hGalp6M0g2cVVtV2sKR/QF8o6ThDTDVMS1/vDKkBELTSFcTDCt
            2Mh9w9FgkquTnNTnew7D5w7kIwkdIbFsvNKGm9Gdi83HQ7yTWETw2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T22:08:39Z"
    mac: ENC[AES256_GCM,data:c+uE1T3OiREW4jS8BkR2ky7ChZB46LW/nQLcEQmag0cwxWtPKDIgYVnodAU9rTQS5Du1CRHiCaO4HNq5bjD5qCdZgHGd3DcEOC88H30KaOBSEum2BnwORAClwTKGBSTZAHBeLqbn2jwe7ff+zcZXoioqF4/Q5bceQRjheq69/Xo=,iv:g4iYojavXPhQEH2BdedBHzmiU7X6YwV6wncz2LA3b2g=,tag:8m+cOBfNSIlussWoVld/kQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
