apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure # Waits for MetalLB/Traefik HelmReleases to be applied
  interval: 10m
  path: ./infrastructure/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
