apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dns-l2
  namespace: metallb-system
spec:
  interfaces:
    - ens18
  ipAddressPools:
    - dns-pool
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: talos-cp-1

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: traefik-l2
  namespace: metallb-system
spec:
  interfaces:
    - ens18
  ipAddressPools:
    - traefik-pool
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: talos-cp-1
    - matchLabels:
        kubernetes.io/hostname: talos-cp-3
