apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lan
  namespace: metallb-system
spec:
  ipAddressPools:
    - dns-pool
    - traefik-pool
    - core-pool
    - jellyfin-pool
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: talos-cp-1
    - matchLabels:
        kubernetes.io/hostname: talos-wk-1
    - matchLabels:
        kubernetes.io/hostname: talos-cp-3