apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - dns-pool
    - lan-pool
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: talos-cp-1
    - matchLabels:
        kubernetes.io/hostname: talos-cp-2
    - matchLabels:
        kubernetes.io/hostname: talos-cp-3
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: traefik-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - traefik-pool
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: talos-cp-1
    - matchLabels:
        kubernetes.io/hostname: talos-cp-2
    - matchLabels:
        kubernetes.io/hostname: talos-cp-3
