apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-values
  namespace: falco
type: Opaque
stringData:
  values.yaml: |
    config:
      gotify:
        hostport: "http://gotify.gotify.svc.cluster.local"
        token: "changeme_after_first_login"
        format: "markdown"
        minimumpriority: "warning"
        checkcert: false