apiVersion: v1
kind: Secret
metadata:
    name: falcosidekick-values
    namespace: falco
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:WG+5X/AnRcfbPQAcxtRT/RF7OyzGIcBaYuP+o0ZMkBwhqTI9gJSD3SN2kWDQxf/dsveBQV+cU5a7d8ej2iXRyCyJI00aNLZewzKD+XVbPYNgkYu2J7posy3TnzAtLBKfOeQuEJIuzcIjYtuz/UP8csIwQxeZ4ZN0brmCX4a52BLDcRDGi7MZLDCSB4sJbixU+hX7OUkFlsTPTUMdHZbQLf247pYyx/j3mzBImQBFpgA=,iv:MYBg7mN79+8ewvgxhGPeXXLrhG/yNvzZc9KhyeyDjKQ=,tag:hvoWaq0rHcTthdw+DCGqQw==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VEhSZmszOVVkKzNnWWtV
            V045cW9xZ3B6ZDZnNTUycVdGR1UwTUkzRXdvCndkK2JFSG1OZnM5SEtuYWhRaHhZ
            Q2JGUVNmdUNtYkZXM20wanNIOUtjUjgKLS0tIFpUWDJYSGVURjhySDQxcDBjYVhH
            WDhGRXdRWFFwby9maFFTQ0JUcmZHdFEKpjexFLp/DfycmkYR/GgUFOP1XxhlzskY
            guwpNi9frYdtPDEPVlcwnD2JHmouHOpjJTAzCT+hUgJJpHTYQKPHAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T21:21:27Z"
    mac: ENC[AES256_GCM,data:14jvsk47AJemcUKvLL5Q08ifs6IV/vlHrvpG8s84jVR0DypNLGsOCqvQsDBn0J9wVIqv5PqmNNwG/VSfiHApwroOOwnb5jWDb/D8sgPPg/hCVdS4cCwrdJKF9C5VNz1pWTK0i+kARgigOkYBMgNmeT12/KcWfGsDh4vBXHbxnmw=,iv:2B2oJehY/ijTTTZxQAVOjhqoLVT0T+TCOrY96C0SZMc=,tag:BQQDNd+2SWIFcQZcBXcwFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
