apiVersion: v1
kind: Secret
metadata:
    name: falcosidekick-values
    namespace: falco
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:0HKKunyChXZ64QYytyXJd6a5VXa+ocSmK7mTCt1oYFc+AaDmh/2WtR8WjeJhE2CG3gYlRtP2sEFdryu4uhR9aHHQWeWxBsncCYLr3mhuH08x9+VYijIB8P4PXooYpeLefTkp3mK5uhoot34UZ8NCC1x8hTlNFJ8dUzUjdsioXDHGTjnpv3yWHRa+BozmVlQxtLmiB/eRtGYM4ALuShR9a94mU7WKdvePs9HaHoQe+xk=,iv:3QeEkGWAWTk/aKYNcaaxU0GTSW+fNIUcrK2DYJhMNCM=,tag:LO2ir9v3sYd0iaBfQ4qnDw==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZy9XNTkwTTNvWjlISHBW
            MUlLZ1NiVVVPT1hqZFpVd0ZHcHZDK2FjaWhVCnMxSURPZ3hlZlVwTDNXdXc1Ky9Q
            aUliQnpMK3FNNjVIMkoxSllIL0JJRU0KLS0tIERYVUNkdzMyeE5YN3ZhQjY5VG0x
            SFVxaXdlbUxkWnRIcjFuM0ZONVRBRlUKTWLaUmbvRDJoofOjR/cPf+7O2aM94olE
            GwP1cPV6MsD548vFz6uEB3aYKNfxRTAZVRKnO98C1B1iClzMko+t9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T18:43:29Z"
    mac: ENC[AES256_GCM,data:pyFfk4EYR/s4bLmbNZY/kfOFLFp7EAOGFemv2r/YwgaxjkiH/bwIk5RtFnjb2nLyA2ie8Tz2/r6mH+33U181tU8CMTBX/Mht8sd3LllJlzIgDw3xgDVTaheF9iYS0CYHV75r7Y50ZJARMsPGyIQx7xMimXFW9tq7CWRDo5lHW5Y=,iv:yqWKKAF9Q39dKtmmQVOXfjw2G8FEBSM4VP1S/wdDSUs=,tag:6aiiJ/jH4Vrj+6/ezUNoCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
