apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    image:
      repository: jellyfin/jellyfin
      tag: latest
    env:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: tank-configs
        mountPath: /config
        subPath: jellyfin
      media:
        enabled: true
        type: pvc
        existingClaim: media
        mountPath: /media
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache
    resources:
      requests:
        memory: "1Gi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1"
    service:
      enabled: true
      type: NodePort
      port: 8096
      nodePort: 30096

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - talos-cp-1
                    - talos-cp-2
                    - talos-cp-3
  
