apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  maxHistory: 2

  chart:
    spec:
      chart: jellyfin
      version: "2.7.0"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    image:
      repository: jellyfin/jellyfin
      tag: 10.11.6@sha256:333b647716631443a43c7fabac4b0c46b4e2f036bad19547e00958f10f721b85
    env:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: tank-configs
        mountPath: /config
        subPath: jellyfin
      media:
        enabled: true
        type: pvc
        existingClaim: media
        mountPath: /media
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache
    resources:
      requests:
        memory: "1Gi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1"
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.2.50
      externalTrafficPolicy: Local
      port: 8096
      extraPorts:
        - name: dlna
          port: 1900
          targetPort: 1900
          protocol: UDP

    initContainers:
      - name: jellyfin-init
        image: alpine:3.21@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
        command: ["/bin/sh", "/scripts/init.sh"]
        volumeMounts:
          - name: init-scripts
            mountPath: /scripts
          - name: config
            mountPath: /config
            subPath: jellyfin

    extraVolumes:
      - name: init-scripts
        configMap:
          name: jellyfin-init
          defaultMode: 0755
          
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - talos-cp-3
