apiVersion: v1
kind: Secret
metadata:
    name: actual-credentials
    namespace: actual-ai
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:khBsqc1beNYHrv/dYmw=,iv:3Yxyrgv1jXtVWqPHROZStQUMJrOZx8QpE4Xq/KSh0w4=,tag:foChRmbvf6Zc/B1dPsxOXA==,type:str]
    budgetId: ENC[AES256_GCM,data:febBlOyyCkX7GeWg+2KR5MNCyeoou8Pg43UKrLFZLkwtKH2S,iv:zBZi2krQBciQOFKiy4EgCR8qBmANy9GvgF6ZgLtmgyY=,tag:VYT+1sqnkX0ndz5MMSw+0Q==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdkhEYyt0dEJ3MFltekhT
            aUwwTUVrNkFFZDF6aEtFa3NoV0J4RmpVbWprCnNxZktCWkFrK21oN2NvN083SFJa
            cVBVWWJYQVYwZXAzL01TdU9VRnMwcDAKLS0tIEo0TUJJVCtIaGxvTkVnQll2cHJO
            eEFpV0YyOHNBeG5WVG5FYkxJZHA4NXcKx4ncMVSQmBHNI7Aq/5ZqqD3t2BsWq1li
            E3vNBAKp8c2r/Ext5O3LL+maFoicL4ubmuO4ZtZtHpw1sQvQXqNnKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:25:08Z"
    mac: ENC[AES256_GCM,data:t60WOY+Y9fl4aw+D+/RPAp0Tq/lGp9SrWqEoi8Eik+qSgcos/p6EsOeO4qfup151UyES6EA8i2PFgSw5PfOmAntL+OUqlsAq1ncm760vyvDAFKvYHJnUtkvbUeG0XnrkpCYLGriAXo50A0zc+nhBRS2jRs3HgRkC4+r3kWOD0bE=,iv:4SB+gl3RX/UZzsE07fkWuUvjZYgCXt8jfci8lpskoGw=,tag:SqVrRmGEqWpdrwLP6rWtIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
