apiVersion: v1
kind: Secret
metadata:
    name: actual-credentials
    namespace: actual-ai
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:khBsqc1beNYHrv/dYmw=,iv:3Yxyrgv1jXtVWqPHROZStQUMJrOZx8QpE4Xq/KSh0w4=,tag:foChRmbvf6Zc/B1dPsxOXA==,type:str]
    budgetId: ENC[AES256_GCM,data:0KVgg8DlwaJJUl4GgRHd+uvIH9yn+kBkXsswtQgLIrw0Vs2T,iv:soZUYqMOKbwBJtI0auTCFLuaeddeWM9CXmFzlWeevqs=,tag:19zzrbAumzD07+Ofadsatw==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdkhEYyt0dEJ3MFltekhT
            aUwwTUVrNkFFZDF6aEtFa3NoV0J4RmpVbWprCnNxZktCWkFrK21oN2NvN083SFJa
            cVBVWWJYQVYwZXAzL01TdU9VRnMwcDAKLS0tIEo0TUJJVCtIaGxvTkVnQll2cHJO
            eEFpV0YyOHNBeG5WVG5FYkxJZHA4NXcKx4ncMVSQmBHNI7Aq/5ZqqD3t2BsWq1li
            E3vNBAKp8c2r/Ext5O3LL+maFoicL4ubmuO4ZtZtHpw1sQvQXqNnKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T14:00:29Z"
    mac: ENC[AES256_GCM,data:eIvb7eWnYJFMFqQ4XU+POoxledOKwuNzxlDq6eWn72BVQxyYYIzZSsNznvCkOflszdb8ioAk0e+PnzJYI9bnoVwlDF/pG4jkCyZ4TZ9Sc5RfV2Lt/1TlofqAlWKs9278AxVwIpp8vRdTFi/C/cT7rYk2gSf9iFf8ZBT+lt/GDa0=,iv:2OsygO1xXqe/IPr4l30p1j2spAW8bb28hCSv46bHMns=,tag:ylw62k9QsVE1DvU0LTMiOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
