apiVersion: v1
kind: Secret
metadata:
    name: actual-credentials
    namespace: actual-ai
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:eQL3w4U2n2ZGQZSzykw=,iv:KLXVXvtb2y6eq5qj6j4ZjlM2YWUquSoOq49I3I4cIRY=,tag:mzcauK6uatgM7MtR/hcq8g==,type:str]
    budgetId: ENC[AES256_GCM,data:bV9pWbhZrCfRRY64ZLQVYO1ktntDM0P0W4lF+nH8lOoe/zTz,iv:HUviW/XM7MiHFMqq8ipi9e+BYsx9KLjeX2WkChQVo0k=,tag:qYg22+g9A6fRpM2NeZXmog==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMUd2a2dmZjZrVDlNT2Nt
            WVVtRjM0M1RvaW9CYnpqc24wV0J4T2g5emtBCmI5U2xRc3JUSXRzUGxvTTA0amRs
            RjkzRkswS2M5Qk1FN3NPZFhCYVdueGcKLS0tIGs4Y01pYXBSdHRTYW4zcXd6RE1i
            bkhVaVZ1ZjFIU1JEUGJLakcvQmVKV3cKXK4QhAx521SELJInK7WF3gi6c6Yu7uU/
            Lc8czh8OAKkIvQqxAZq5Cz9hu6W+nq6TVBg33SC+9+qyK3kNs8aKQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T12:43:07Z"
    mac: ENC[AES256_GCM,data:5qBVsV7vCIqjSBmm+4vnNnzRwB0LZCKtcDNiQJMMbonO01gkiVDa5r5bVug4jISnRq2oUady8kppK/dsv8h/+RcV81hgcND7KhCh0/aJVIxeLH+Ra40jkcxXlLkazh/So/366sZhunsmLW5eVz/5Y+QsYokPuVGx7EZKNPNKmeQ=,iv:RggS2E8lEvRnmIz+g8t53zGK4yKugVBav+C8CMCawhk=,tag:PWm9ZncHs5Id5cGWCNmpHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
