apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 1h
  timeout: 20m
  chart:
    spec:
      chart: renovate
      version: "41.x"
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system

  values:
    cronjob:
      schedule: "10 3 * * *"
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 2

    envFrom:
      - secretRef:
          name: renovate-secret
    # env:
    #   LOG_LEVEL: debug

    renovate:
      config: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "platform": "github",
          "token": "${RENOVATE_TOKEN}",

          "repositories": [
            "jobdouma/k8s-home-server"
          ],

          "extends": ["config:recommended"],

          "baseBranchPatterns": ["main"],

          "dependencyDashboard": true,
          "dependencyDashboardAutoclose": true,

          "enabledManagers": ["kubernetes", "flux"],

          "kubernetes": {
            "managerFilePatterns": [
              "/clusters/.+\\.ya?ml$/",
              "/infrastructure/.+\\.ya?ml$/",
              "/apps/.+\\.ya?ml$/"
            ]
          },

          "flux": {
            "managerFilePatterns": [
              "/clusters/.+\\.ya?ml$/",
              "/infrastructure/.+\\.ya?ml$/",
              "/apps/.+\\.ya?ml$/"
            ]
          },

          "prConcurrentLimit": 5,
          "branchConcurrentLimit": 5,
          "automerge": false,

          "packageRules": [
            {
              "matchUpdateTypes": ["minor", "patch", "digest"],
              "groupName": "all non-major updates",
              "groupSlug": "all-non-major"
            }
          ]
        }

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi
