apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:qw38zNYq7dAlETy++BsjYzW9R/3MHEgZ+inAEHGdBCXG3wvMXOTvSDmd3WvvZ3py1/d9PxUrp7xgp5VgLyN2bwTAFWZGWi7XCjxqQ3K+ijZNHvKSiB0tjomybeT7,iv:FQdinTwQkUDrUBQ4Nram5xcKRQTAcVqU0ArHgcJsO7E=,tag:gMa+PDDRbPycQ39l3WNyew==,type:str]
    RENOVATE_GOTIFY_TOKEN: ENC[AES256_GCM,data:dLQa9hdk6qriyd0BUkDf,iv:mrOncfif1iz+MThIIfMtddwFQE36wHPsfuG6VwLyNnU=,tag:AsHd4g72EVOBAvfsZgrw9A==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWDJBOFVQY2VJMjU1RkJo
            RmhEUVAyVWp0NVE4N3FhNks1NFAvZHRqNjBrCnlsSmNBYUkxcGNaNG53WnBmK2Vw
            TDlla0VEcS9yNlJYUmVXdEpQTWkzMVEKLS0tIG04TEpDdjY3V3JNUVJsK0hRMklQ
            Q3dpRXZCcG5sSDVWQjZ1STBrTCttVFEKDeUFukDoDz++nROKylyMZ56YNOqS9OO4
            j6THnCzyMzfgLMy3EMIqZqXy4PF3MOVZmPguDGgo2K1AU2EeWmzswA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T10:19:53Z"
    mac: ENC[AES256_GCM,data:xDNx7hblp2ypEKGqZ5FgxCKaFFBm/sM4kQP2FLgmJ5RgQHbpDeWVOdUjLi9Il43NNcFdZnGL8t6sD7Sm2os+5oLuFd6WU8+5X9NHJgBpTWv3ibrps9E6of+eTvqyhvBhFqWeuCdA6IxP+a7Zc6u2Im0thz8SVN3K1PNDRhMpjCw=,iv:hUy+DKHnKfiRXEEd2TnIiybVNUF7Bc2LoAdCCtk6114=,tag:xyZJOr8VAmNJPzfAy3OYhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
