apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: 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
