apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:B2Fh6pT4aaNzO3eYl8ujBucHBHQusx+7T8zic8q54WruW0c6g59Z6RGjprGPA4cLHwtrJU6DF4QkkZ07CKtfffoH+uyWXtDqKcwRz1S4CkhkN0GGy0YCwJlETVbt,iv:bVs7iRIHw8nQbYUQ6lXAwbXFrSBrmAfhpYAQZBlo1T0=,tag:ct5ppu4FnHkcBzElXhrQRQ==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWmhIUTVrdE9HY1Z3ZklD
            K1JnUzY3dWRpSkpwS1V4VzR5Y1BLVGkxbDNrCmdHemVnMjRpRFYralBJZlBUSUVn
            V3VrU2lUWi9MQ0V6VDk2Rk1PdTlqOVUKLS0tIEpsYjNBdXpraFJXeWNndXBpSCto
            clNVY2NvU0R6cFAzYWNMbkdoQzVXbzgKEg9ZNVmDESUO4YaJ9Aqh2SCUyb1GlJi+
            8lROnlWUmdRzv0OoiB0eFLPwC9ILWBGKXPixHwKmYvjJ3A9fVewa8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T19:06:46Z"
    mac: ENC[AES256_GCM,data:uIw5z6slFUHOIxgKDqPhaX897vOBUkexW2G0tYDMiSCHIineTqUr5OV15aE3MRLbTlh7EJG2FDsKJUkm2yrUWhXmdnCEhViaFa/HgZ4cwbqTvAi5uNc34yC+jhYOEieSkIX6WNP8S3ky1IqnKECnT8Nw9EFHzo6m2/wohZfE7qg=,iv:DgykJfGOkoYJ3NzLOaf81YD9CgHZ+IElmfO1XtOpgP4=,tag:uF6T8XpCBsvUeJbJIPjHwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
