apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: media
  labels:
    app: recyclarr
data:
  recyclarr.yml: |
    sonarr:
      base_url: ${SONARR_URL}
      api_key: ${SONARR_APIKEY}
    radarr:
      base_url: ${RADARR_URL}
      api_key: ${RADARR_APIKEY}