apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr-cronjob
  namespace: media
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 7200
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          volumes:
            - name: config-file
              configMap:
                name: recyclarr-config
            - name: app-data
              emptyDir: {}
          containers:
            - name: recyclarr
              image: ghcr.io/recyclarr/recyclarr:8.5.1@sha256:734cecf44ae9be7cf0cb05b2c1bc7da0abef9d938cc11b605e58b3146205e5c0
              imagePullPolicy: IfNotPresent
              args: ["sync"]
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                readOnlyRootFilesystem: true
              env:
                - name: TZ
                  value: Europe/Amsterdam
                - name: RECYCLARR_CONFIG_DIR
                  value: /config
                - name: RECYCLARR_DATA_DIR
                  value: /tmp/recyclarr
                - name: RADARR_URL
                  valueFrom:
                    secretKeyRef:
                      name: recyclarr-secrets
                      key: radarr_url
                - name: RADARR_APIKEY
                  valueFrom:
                    secretKeyRef:
                      name: recyclarr-secrets
                      key: radarr_apikey
                - name: SONARR_URL
                  valueFrom:
                    secretKeyRef:
                      name: recyclarr-secrets
                      key: sonarr_url
                - name: SONARR_APIKEY
                  valueFrom:
                    secretKeyRef:
                      name: recyclarr-secrets
                      key: sonarr_apikey
              volumeMounts:
                - name: config-file
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
                - name: app-data
                  mountPath: /tmp/recyclarr