apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secrets
  namespace: media
type: Opaque
stringData:
  radarr_url: http://radarr.media.svc.cluster.local:7878
  radarr_apikey: 259a95c5c32143f9afee5a513b438efa
  sonarr_url: http://sonarr.media.svc.cluster.local:8989
  sonarr_apikey: d9d2db96fd524eb5a1b0120204b5a104