apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: media
data:
  recyclarr.yml: |
    radarr:
      movies:
        base_url: !secret radarr_url
        api_key: !secret radarr_apikey
        replace_existing_custom_formats: true
        delete_old_custom_formats: false
        include:
          - template: radarr-quality-definition-movie
          - template: radarr-quality-profile-remux-web-2160p
          - template: radarr-custom-formats-remux-web-2160p
          - template: radarr-quality-profile-hd-bluray-web
          - template: radarr-custom-formats-hd-bluray-web

    sonarr:
      series:
        base_url: !secret sonarr_url
        api_key: !secret sonarr_apikey
        replace_existing_custom_formats: true
        delete_old_custom_formats: false
        include:
          # Required base definition
          - template: sonarr-quality-definition-series

          # Profile 1: HD-1080p (default / sweet spot)
          - template: sonarr-quality-profile-hd-1080p

          # Profile 2: HD-2160p (4K)
          - template: sonarr-quality-profile-hd-2160p
