apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: media
type: Opaque
stringData:
    radarr_url: ENC[AES256_GCM,data:/2+QYWWojE0IhJ7/8YHNfzxMIfljiKwVPQ+IsCmkawlYnwt/5xOt2SZV,iv:TDYQWFz9Qr87npZgPBkMKCHLLxEvsMS8ROAVbNVAjZg=,tag:a1nTCibsEVK2aF+j/hA4NQ==,type:str]
    radarr_apikey: ENC[AES256_GCM,data:gVhack4LzqMoCpWKLZSHU8vXFvNFKY6S165mhMamNFA=,iv:DSuWwxSsKy5wZhl8FOUIBMVswvRLsTLSk8UWI6YlwBE=,tag:KxROYuwIngY1NFkJOiuXEg==,type:str]
    sonarr_url: ENC[AES256_GCM,data:sO/LT7P80LKitn10fPTWMmSr70JjLl7VAq0B8y+B92RVzV/8LG2W9ww9,iv:mQxTMSh1Ui0i6ynbqtjaNupdVCKRIToJblTArjLYJuA=,tag:q3rIZuUpHUMaugyF0qTSeQ==,type:str]
    sonarr_apikey: ENC[AES256_GCM,data:N2HZfXZeMsg0x+83eQty3J2uyweSY9v+AqiNhrL83wM=,iv:1NvUfdSzvmF/cXX6NqiO4b0UJ5zc5eR9j8Y9KzySXj8=,tag:S1pX0puZBIw4TjyMp2DuQA==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY3RnWkxOSU5IbUlWMzNW
            eGgrSEREcnYxSkZPUTAvajRyMlBPbXJNbUVRCkxLS1h2L0J5S0lTWS95d0NGSjM3
            Q0MwUnlxYWdhZUJLSVRFVGxRQU40bE0KLS0tIHJnTzRCZFVqdVlubHpPYzRHNWtL
            NVZOWW9MUEZ2aWhwZGIxYUcvUXlkbUUKV8qWUj8inJ8hRgGAjX4QrTyTpjiuf9pH
            OfdxT1VCa0icXi1ofVyJdpXBDhN63J+suupMbuymrIdXCXaHyWS+dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T19:05:58Z"
    mac: ENC[AES256_GCM,data:Exo+XyOgt/2W3U/YxZIuwQFWF7aMY1I5VkL0NSwPoDRAbXunVJV6ZOudEKGx8wPkobppWbbDdiFzzraNvotF8V/RUzgvTx9lN4QaPOateAibECIiWyR+cGYebEbPx63Ddu4d8wXEunUcG9NxyU93qJjf0HYJy7ixSPKaJkfIFNU=,iv:f2PQ3MSSaCcejuz812udo4NStg+AdftcneWycWr2g/Q=,tag:UG2pgfa0rxd0o0rLktYyIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
