apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: media
type: Opaque
stringData:
    secrets.yml: ENC[AES256_GCM,data:KSNJqLpukJzd3iC0nmgh5yOsKpCWtkAKPRelt25u6825pUEgjP9wekX49aF9IOWMvOy7MuritSzzMwunT4xZv1agBxn0L7332Xmd3Y9cvSudsz5MRUYAzipd45qYFc/jeMIU6ksGyF0KYBOgvAr8LKGJUaDA6v+K65CiGik7vtkXCjaPjXnx/NE9fOICaeTr4RzHe8MY/bpc55FZ2ZUUXDeVOdo7snfCeSdRMmLYNWg7FaNGDq0+ZLrNJJsUT9C11ksc6Qf25D43B06HPxI=,iv:6LR4WvDurb9QddUA0f5oVVsfnc5n53fVsvPTvGzj1aA=,tag:MxuOM84SFENxuQ038iaQ8w==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TXVvenlnNzFvYlA5OTM1
            cjFzU0J3SXJtR2JKS0pzcUxpSGdDVE5haXlBCm1DWjVNZlIyV1BiTWU0WUZ4M0k2
            OVRWT2ZISW52VEdXUCs0QTFSYzV2Ym8KLS0tIHRQU0Z3cDJUZUU1amFvVGgzczhX
            U01tZ0M0Rm1uN0NFd1NqTG1xRVROQTAKfd7qcYt3Uw5h8BQ/JtPGrRyAw0luok7F
            tp5UaklZpdXxxuP9u8vJKxlmHLR+J+kkq+3uX8JLXHMySmY/dRlTmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T20:41:06Z"
    mac: ENC[AES256_GCM,data:/EQFfzhO2Ro0rgmrCBCWTaPWw9ZB05tvaHEjvCQ1w7HoilLB5a1DygOxcN2yfxY8QMliDyEe1lMWvjMFJSkTanANMXdsq/+6uAL+jOrhD2XR72W+x0u6Fp1cPQcCkEjohm+O4LbXnpYL25xqH3DJNW6deBZtTBkZpBQOzOlL3bU=,iv:MkJ9v9dJoEtTjAsE8v6NQuDgZXALzGyRVZ6Y/94Ypww=,tag:70KP2yiNdh0twWvIrmDKmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
