apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:jEGbQRY=,iv:390mXW00vm7p+C7NfZO9ZGhbczOEF9igaoT6QNPYj4Q=,tag:HTGOEyNf0I/LP8SolhvSuw==,type:str]
    admin-password: ENC[AES256_GCM,data:IZbvtOazAgaXv1iQ4GmfLWtTte3s,iv:o14erxjUeFxNIQobDEBrNqLxu3FZI6eZvpuA+hqdWLg=,tag:fI4UnqPtFBCHSvfYCm4uDQ==,type:str]
sops:
    age:
        - recipient: age18zx3u4cnpe3y55rruzp5v4uregm0kxe2ge6wzle54nu9vlxlndmqweckld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNFJIcTJHeXFQTWtxKzd0
            M1RhZCt5NExCSWNqdlNLV2pGRlJoT1FneDJ3CjhVMC90aDJ6anFBN1hZNXVXK3N4
            MEsxRkZzb3JZMWFXaW5wQmQ0N1Jlb2sKLS0tIE1TeEhmNGVrTlgzZ2d1ejY3NktD
            QUl0TzhkOEJ6TGJ5L2hsb2xXZ2dreGsKE+17eIQIg1HcqjOPT/OqDsRXJv9Ia0XP
            DuoR+nx7DCL6DSONwlPvybht5ZmtMru+dfMJHol+IBPdmwiUxwH5cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T21:00:56Z"
    mac: ENC[AES256_GCM,data:jDKETQzC+GUDZxAOw+UplxhMTm8yIJbXRAaXZEdfhISmOYK77jTDA3UQoEewzwqeMKBJOrtADgUNoKkNcKxtqm7aG1HmvjaN+YkUrvTZUPKu3rZsMgHo623zq4MMjRW2WH3JlGVBiGz4ICcLyKy91g7Q8bRil914i3U6fcuDbUU=,iv:D+cJ8NDJK2vQJ0f4F/+4szU6nYwga0fR/q67kMLVmjA=,tag:ZZQ9zgs+ReCVZjwQ+CxtaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
