apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  timeout: 60m

  chart:
    spec:
      chart: kube-prometheus-stack
      version: "82.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3

  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3

  values:
    prometheus:
      service:
        type: ClusterIP
        port: 9090

      prometheusSpec:
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}

    prometheus-node-exporter:
      enabled: true
      hostRootFsMount:
        enabled: false
    
    grafana:
      admin:
        existingSecret: grafana-admin

