apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  endpoints:
    - targetPort: 8080
      interval: 30s
