apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Storage
  - storage/namespace.yaml
  - storage/pv-media.yaml
  - storage/pv-tank-configs.yaml
  - storage/pvc-media.yaml
  - storage/pvc-tank-configs.yaml

  # Controllers (Base)
  - traefik/base
  - metallb/base/namespace.yaml
  - metallb/base/helmrelease.yaml
  - metallb/base/helmrepository.yaml
