apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Storage
  - storage/namespace.yaml
  - storage/pv-media.yaml
  - storage/pv-tank-configs.yaml
  - storage/pvc-media.yaml
  - storage/pvc-tank-configs.yaml

  - traefik/namespace.yaml
  - traefik/helmrepository.yaml
  - traefik/helmrelease.yaml
  - traefik/ingressroute.yaml
  - traefik/middlewares.yaml

  - metallb/namespace.yaml
  - metallb/helmrelease.yaml
  - metallb/helmrepository.yaml
  - metallb/config/ipaddress-pools.yaml
  - metallb/config/l2-advertisements.yaml

  - headlamp/namespace.yaml
  - headlamp/helmrepository.yaml
  - headlamp/helmrelease.yaml
  - headlamp/ingressroute.yaml
  - headlamp/serviceaccount.yaml
  - headlamp/oidc-secret.yaml

  - longhorn/namespace.yaml
  - longhorn/helmrepository.yaml
  - longhorn/helmrelease.yaml

  - authentik/namespace.yaml
  - authentik/helmrepository.yaml
  - authentik/helmrelease.yaml
  - authentik/ingressroute.yaml
  - authentik/secret.yaml
  - authentik/postgresql-secret.yaml