apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Storage
  - storage/namespace.yaml
  - storage/pv-media.yaml
  - storage/pv-tank-configs.yaml
  - storage/pvc-media.yaml
  - storage/pvc-tank-configs.yaml

  - traefik/namespace.yaml
  - traefik/helmrepository.yaml
  - traefik/helmrelease.yaml
  - traefik/ingressroute.yaml
  - traefik/middlewares.yaml
  - traefik/servicemonitor.yaml
  - traefik/certificate.yaml
  - traefik/clusterrole.yaml
  - traefik/pdb.yaml

  - metallb/namespace.yaml
  - metallb/helmrelease.yaml
  - metallb/helmrepository.yaml
  - metallb/config/ipaddress-pools.yaml
  - metallb/config/l2-advertisements.yaml

  - headlamp/namespace.yaml
  - headlamp/helmrepository.yaml
  - headlamp/helmrelease.yaml
  - headlamp/ingressroute.yaml
  - headlamp/oidc-secret.yaml
  - headlamp/networkpolicy.yaml
  - headlamp/rbac.yaml
  - headlamp/certificate.yaml

  

  - authentik/namespace.yaml
  - authentik/certificate.yaml
  - authentik/helmrepository.yaml
  - authentik/helmrelease.yaml
  - authentik/ingressroute.yaml
  - authentik/secret.yaml
  - authentik/postgresql-secret.yaml
  - authentik/networkpolicy.yaml
  - authentik/pdb-server.yaml
  - authentik/pdb-worker.yaml
  - authentik/blueprints-secret.yaml

  # ──────────────────────────────────────
  # Kube Metrics Server
  # ──────────────────────────────────────
  - metrics-server/helmrepository.yaml
  - metrics-server/helmrelease.yaml

  - cert-manager/namespace.yaml
  - cert-manager/helmrepository.yaml
  - cert-manager/helmrelease.yaml
  - cert-manager/ca-certificate.yaml
  - cert-manager/clusterissuer-ca.yaml
  - cert-manager/clusterissuer-selfsigned.yaml

  - local-path-storage
