apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-arr-to-qbittorrent
  namespace: media
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: sonarr
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: radarr
      ports:
        - protocol: TCP
          port: 8080
