apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: renovate-allow-all-egress
  namespace: renovate
spec:
  podSelector: {}  # all pods in this namespace
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
