apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik
  namespace: media
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: networking
      ports:
        - protocol: TCP
          port: 8080   # dashy + qbittorrent
        - protocol: TCP
          port: 8096   # jellyfin
        - protocol: TCP
          port: 5055   # jellyseerr
        - protocol: TCP
          port: 8989   # sonarr
        - protocol: TCP
          port: 7878   # radarr
