apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ──────────────────────────────────────
  # Blocky (DNS)
  # ──────────────────────────────────────
  - blocky/namespace.yaml
  - blocky/configmap.yaml
  - blocky/helmrepository.yaml
  - blocky/helmrelease.yaml
  - blocky/servicemonitor.yaml

  # ──────────────────────────────────────
  # Jellyfin
  # ──────────────────────────────────────
  - jellyfin/helmrepository.yaml
  - jellyfin/helmrelease.yaml

  # ──────────────────────────────────────
  # qBittorrent
  # ──────────────────────────────────────
  - qbittorrent/helmrepository.yaml
  - qbittorrent/helmrelease.yaml

  # ──────────────────────────────────────
  # monitoring / prometheus
  # ──────────────────────────────────────
  - monitoring/namespace.yaml
  - monitoring/monitoring-release.yaml
  - monitoring/monitoring-repo.yaml
  - monitoring/servicemonitor.yaml

  # ──────────────────────────────────────
  # Jellyseerr
  # ──────────────────────────────────────
  - jellyseer/helmrelease.yaml

  # ──────────────────────────────────────
  # MetalLB (LoadBalancer)
  # ──────────────────────────────────────
  - metallb/namespace.yaml
  - metallb/helmrepository.yaml
  - metallb/helmrelease.yaml
  - metallb/config/ipaddress-pool.yaml
  - metallb/config/l2-advertisement.yaml
