apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ──────────────────────────────────────
  # Blocky (DNS)
  # ──────────────────────────────────────
  - blocky/namespace.yaml
  - blocky/configmap.yaml
  - blocky/helmrepository.yaml
  - blocky/helmrelease.yaml
  - blocky/servicemonitor.yaml
  - blocky/ingressroute.yaml
  - blocky/certificate.yaml
  - blocky/pdb.yaml

  # ──────────────────────────────────────
  # Jellyfin
  # ──────────────────────────────────────
  - jellyfin/helmrepository.yaml
  - jellyfin/helmrelease.yaml
  - jellyfin/ingressroute.yaml
  - jellyfin/certificate.yaml

  # ──────────────────────────────────────
  # qBittorrent
  # ──────────────────────────────────────
  - qbittorrent/helmrelease.yaml
  - qbittorrent/secret.yaml
  - qbittorrent/ingressroute.yaml
  - qbittorrent/certificate.yaml

  # ──────────────────────────────────────
  # monitoring / prometheus
  # ──────────────────────────────────────
  - prometheus/namespace.yaml
  - prometheus/helmrepository.yaml
  - prometheus/helmrelease.yaml
  - prometheus/ingressroute.yaml
  - prometheus/service.yaml
  - prometheus/certificate.yaml
  - prometheus/pdb.yaml

  # ──────────────────────────────────────
  # Grafana
  # ──────────────────────────────────────
  - grafana/ingressroute.yaml
  - grafana/admin-secret.yaml
  - grafana/certificate.yaml
  - grafana/dashboards/

  # ──────────────────────────────────────
  # Promtail
  # ──────────────────────────────────────
  - promtail/helmrelease.yaml

  # ──────────────────────────────────────
  # Loki
  # ──────────────────────────────────────
  - loki/helmrepository.yaml
  - loki/helmrelease.yaml
  - loki/servicemonitor.yaml
  - loki/pdb.yaml

  # ──────────────────────────────────────
  # Jellyseerr
  # ──────────────────────────────────────
  - jellyseerr/helmrelease.yaml
  - jellyseerr/ingressroute.yaml
  - jellyseerr/pvc.yaml
  - jellyseerr/certificate.yaml

  # ──────────────────────────────────────
  # Network Policies
  # ──────────────────────────────────────
  - networkpolicies/allow-all-kube-system.yaml
  - networkpolicies/allow-renovate-egress.yaml
  - networkpolicies/allow-dns-from-lan.yaml
  - networkpolicies/allow-all-metallb.yaml

  # ──────────────────────────────────────
  # Sonarr
  # ──────────────────────────────────────
  - sonarr/pvc.yaml
  - sonarr/helmrelease.yaml
  - sonarr/ingressroute.yaml
  - sonarr/certificate.yaml

  # ──────────────────────────────────────
  # Radarr
  # ──────────────────────────────────────
  - radarr/pvc.yaml
  - radarr/helmrelease.yaml
  - radarr/ingressroute.yaml
  - radarr/certificate.yaml

  # ──────────────────────────────────────
  # Renovate
  # ──────────────────────────────────────
  - renovate/namespace.yaml
  - renovate/secret.yaml
  - renovate/helmrepository.yaml
  - renovate/helmrelease.yaml

  # ──────────────────────────────────────
  # Renovate
  # ──────────────────────────────────────
  - dashy/configmap.yaml
  - dashy/helmrelease.yaml
  - dashy/ingressroute.yaml
  - dashy/certificate.yaml

  # ──────────────────────────────────────
  # Prowlarr
  # ──────────────────────────────────────
  - prowlarr/pvc.yaml
  - prowlarr/helmrelease.yaml
  - prowlarr/ingressroute.yaml
  - prowlarr/certificate.yaml

  # ──────────────────────────────────────
  # Reloader
  # ──────────────────────────────────────
  - stakater-reloader/helmrepository.yaml
  - stakater-reloader/helmrelease.yaml
  - stakater-reloader/servicemonitor.yaml

  # ──────────────────────────────────────
  # Sabnzbd
  # ──────────────────────────────────────
  # - sabnzbd/helmrelease.yaml
  # - sabnzbd/ingressroute.yaml

  # ──────────────────────────────────────
  # Recyclarr
  # ──────────────────────────────────────
  - recyclarr/configmap.yaml
  - recyclarr/secret.yaml
  - recyclarr/cronjob.yaml

  # ──────────────────────────────────────
  # Joplin
  # ──────────────────────────────────────
  - joplin/namespace.yaml
  - joplin/secret.yaml
  - joplin/hr-postgres.yaml
  - joplin/hr-joplin.yaml
  - joplin/ingressroute.yaml
  - joplin/certificate.yaml

  # ──────────────────────────────────────
  # TrueNAS NFS dynamic provisioner
  # ──────────────────────────────────────
  - truenas-nfs/helmrepository.yaml
  - truenas-nfs/helmrelease.yaml

  # ──────────────────────────────────────
  # CoreDNS to Blocky
  # ──────────────────────────────────────
  - coredns/configmap.yaml
  - coredns/servicemonitor.yaml

  # ──────────────────────────────────────
  # FreshRSS
  # ──────────────────────────────────────
  - freshrss/namespace.yaml
  - freshrss/opml-configmap.yaml
  - freshrss/helmrelease.yaml
  - freshrss/ingressroute.yaml
  - freshrss/certificate.yaml

  # ──────────────────────────────────────
  # Falco
  # ──────────────────────────────────────
  - falco/namespace.yaml
  - falco/helmrepository.yaml
  - falco/helmrelease.yaml
  - falco/falcosidekick-helmrelease.yaml
  - falco/ingressroute.yaml
  - falco/servicemonitor.yaml
  - falco/certificate.yaml
  - falco/configmap.yaml

  # ──────────────────────────────────────
  # Velero (K8s-backup)
  # ──────────────────────────────────────
  - velero/namespace.yaml
  - velero/pvc.yaml
  - velero/minio-secret.yaml
  - velero/minio.yaml
  - velero/helmrepository.yaml
  - velero/helmrelease.yaml
  - velero/servicemonitor.yaml
  - velero/networkpolicy.yaml

  # ──────────────────────────────────────
  # Ntfy
  # ──────────────────────────────────────
  - ntfy/namespace.yaml
  - ntfy/secret.yaml
  - ntfy/helmrelease.yaml
  - ntfy/certificate.yaml
  - ntfy/ingressroute.yaml
